# Names SparkLab accepts (runtime/sparklab). Not PySpark: nothing here runs.
from typing import Any

def avg(*args: Any, **kwargs: Any) -> Any: ...
def broadcast(*args: Any, **kwargs: Any) -> Any: ...
def coalesce(*args: Any, **kwargs: Any) -> Any: ...
def col(*args: Any, **kwargs: Any) -> Any: ...
def count(*args: Any, **kwargs: Any) -> Any: ...
def countDistinct(*args: Any, **kwargs: Any) -> Any: ...
def date_trunc(*args: Any, **kwargs: Any) -> Any: ...
def lag(*args: Any, **kwargs: Any) -> Any: ...
def lead(*args: Any, **kwargs: Any) -> Any: ...
def lit(*args: Any, **kwargs: Any) -> Any: ...
def max(*args: Any, **kwargs: Any) -> Any: ...
def min(*args: Any, **kwargs: Any) -> Any: ...
def row_number(*args: Any, **kwargs: Any) -> Any: ...
def sum(*args: Any, **kwargs: Any) -> Any: ...
def to_date(*args: Any, **kwargs: Any) -> Any: ...
def when(*args: Any, **kwargs: Any) -> Any: ...
