"""Generate content/pylance-stubs from the imports the Datapass readers accept.

Exercise files import pyspark, airflow, pendulum or mlflow. Datapass never installs those packages:
SparkLab and the Airflow Lab reader parse the files with a whitelisted AST reader and never import them.
Pylance therefore reports every such import as unresolved. These stubs declare exactly the modules and
names the readers accept, so Pylance resolves them (and completes them) without any package installed.
They are typing information only: nothing here is executed, and they are not the real packages. They are
written as .py modules, not .pyi stubs: Pylance reports a .pyi without a matching source as "could not be
resolved from source", which is the warning this removes. Nothing puts this folder on Python's import path.

The extension copies them to `.datapass/pylance-stubs/` in the workspace and adds that folder to
`python.analysis.extraPaths` when an exercise is opened (src/exerciseWorkspace.ts).

Run from the repository root with PYTHONPATH=runtime. `--check` fails when the committed stubs differ.
"""
from __future__ import annotations

import argparse
import sys
from pathlib import Path

from airflowlab.parser import IMPORTS as AIRFLOW_IMPORTS
from sparklab.safe_parser import ML_IMPORTS, MLFLOW_MODULES
from sparklab.sparklab import functions as spark_functions

ROOT = Path.cwd()
OUT = ROOT / "content" / "pylance-stubs"
STDLIB = {"datetime"}

AIRFLOW_HEADER = "# Names the Datapass Airflow Lab reader accepts (runtime/airflowlab). Not Apache Airflow."
SPARK_HEADER = "# Names SparkLab accepts (runtime/sparklab). Not PySpark: nothing here runs."
MLFLOW_HEADER = "# The MLflow subset SparkLab notebooks can call (runtime/sparklab/mlflow_api.py). Not MLflow."
NOTEBOOK_HEADER = "# Notebook utilities SparkLab binds in Fabric and Synapse notebooks. Not the Microsoft package."
PENDULUM_HEADER = "# Names the Datapass Airflow Lab reader accepts from pendulum. Not the pendulum package."
PACKAGE_HEADER = "# Package marker for the Datapass Pylance stubs (see content/pylance-stubs/README.md)."


def spark_function_names() -> list[str]:
    return sorted(name for name in dir(spark_functions) if not name.startswith("_"))


def modules() -> dict[str, tuple[str, list[str], bool]]:
    """module -> (header, declared names, open-ended). Open-ended modules resolve any attribute."""
    result: dict[str, tuple[str, list[str], bool]] = {}
    for module, names in AIRFLOW_IMPORTS.items():
        if module in STDLIB:
            continue
        header = PENDULUM_HEADER if module == "pendulum" else AIRFLOW_HEADER
        result[module] = (header, sorted(names), False)
    result["pyspark.sql"] = (SPARK_HEADER, ["Window", "functions"], False)
    result["pyspark.sql.window"] = (SPARK_HEADER, ["Window"], False)
    result["pyspark.sql.functions"] = (SPARK_HEADER, spark_function_names(), False)
    for module, names in ML_IMPORTS.items():
        result[module] = (SPARK_HEADER, sorted(names), False)
    for module in MLFLOW_MODULES:
        result[module] = (MLFLOW_HEADER, [], True)
    result["notebookutils"] = (NOTEBOOK_HEADER, ["mssparkutils"], True)
    result["mssparkutils"] = (NOTEBOOK_HEADER, [], True)
    return result


def stub_path(module: str, packages: set[str]) -> Path:
    parts = module.split(".")
    if module in packages:
        return OUT.joinpath(*parts, "__init__.py")
    return OUT.joinpath(*parts[:-1], parts[-1] + ".py")


def render(module: str, header: str, names: list[str], open_ended: bool, submodules: set[str]) -> str:
    lines = [header, "from typing import Any", ""]
    for name in names:
        if f"{module}.{name}" in submodules:
            lines.append(f"from . import {name} as {name}")
        elif module == "pyspark.sql.functions":
            lines.append(f"def {name}(*args: Any, **kwargs: Any) -> Any: ...")
        else:
            lines.append(f"{name}: Any")
    if open_ended:
        lines.append("def __getattr__(name: str) -> Any: ...")
    return "\n".join(lines).rstrip() + "\n"


def generate() -> dict[Path, str]:
    declared = modules()
    # Every dotted prefix of a declared module is a package; packages get an __init__.py.
    packages = {".".join(m.split(".")[:i]) for m in declared for i in range(1, len(m.split(".")))}
    files: dict[Path, str] = {}
    for package in sorted(packages - set(declared)):
        files[stub_path(package, packages)] = PACKAGE_HEADER + "\n"
    for module, (header, names, open_ended) in sorted(declared.items()):
        files[stub_path(module, packages)] = render(module, header, names, open_ended, set(declared))
    files[OUT / "README.md"] = README
    return files


README = """# Pylance stubs for Datapass exercises

Generated by `scripts/authoring/gen_pylance_stubs.py`. Do not edit by hand.

Exercise and notebook files import `pyspark`, `airflow`, `pendulum` or `mlflow`. Datapass never installs those
packages: SparkLab and the Airflow Lab reader parse the files and never import them. These stubs declare the
modules and names those readers accept, so Pylance resolves the imports instead of flagging them.

They are typing information only, written as `.py` modules so Pylance does not report them as stubs without a
source. Nothing in them runs and nothing puts this folder on Python's import path. They are not the real packages:
a name missing here is a name the Datapass reader refuses.
"""


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true", help="fail when the committed stubs differ")
    args = parser.parse_args()
    files = generate()
    existing = {p for p in OUT.rglob("*") if p.is_file()} if OUT.exists() else set()
    stale = sorted(existing - set(files))
    changed = sorted(p for p, text in files.items() if not p.exists() or p.read_text(encoding="utf-8") != text)
    if args.check:
        if stale or changed:
            for path in stale + changed:
                print(f"out of date: {path.relative_to(ROOT).as_posix()}", file=sys.stderr)
            print("Run: PYTHONPATH=runtime python scripts/authoring/gen_pylance_stubs.py", file=sys.stderr)
            return 1
        print(f"Pylance stubs up to date ({len(files)} files).")
        return 0
    for path in stale:
        path.unlink()
    for path, text in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8", newline="\n")
    print(f"Wrote {len(files)} files to {OUT.relative_to(ROOT).as_posix()}.")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
