"""Generate schemas/*.schema.json from the runtime's pydantic contracts (the one source of truth).

VS Code validates and completes these files with them (package.json contributes.jsonValidation):
- bi-model.schema.json: the BI Lab star model, bi/model.json (runtime/bilab/model.py StarModel);
- mission.schema.json: a missionlab mission.json, dbt / Terminal / Infra Lab packs (runtime/missionlab/model.py);
- api-mission.schema.json: an API Lab mission.json (runtime/apilab/model.py);
- exercise-pack.schema.json: an exercise pack's manifest.json (runtime/datapass_runtime/exercise_packs.py).
schemas/project.schema.json (.datapass/project.json) is written by hand: its validator is the extension's
(src/project/projectManifestModel.ts), not a pydantic model.

Run from the repository root with PYTHONPATH=runtime. `--check` fails when the committed schemas differ.
"""
from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

from pydantic.json_schema import GenerateJsonSchema

from apilab.model import Mission as ApiMission
from bilab.model import StarModel
from datapass_runtime.exercise_packs import PackManifest
from missionlab.model import Mission

ROOT = Path.cwd()
OUT = ROOT / "schemas"
SCHEMAS = {
    "bi-model": (StarModel, "Datapass BI Lab star model (bi/model.json)"),
    "mission": (Mission, "Datapass mission (dbt, Terminal and Infra Lab packs)"),
    "api-mission": (ApiMission, "Datapass API Lab mission"),
    "exercise-pack": (PackManifest, "Datapass exercise pack manifest"),
}


# BeforeValidators that turn a list of lines into the text (missionlab's Lines and FileText): the file may hold either.
LINE_JOINERS = {"_join_lines", "_file_text"}


class FileSchema(GenerateJsonSchema):
    """The schema of the JSON a file may hold: what a BeforeValidator accepts, not only what it produces."""

    def function_before_schema(self, schema):
        inner = super().function_before_schema(schema)
        if getattr(schema["function"]["function"], "__name__", "") in LINE_JOINERS:
            return {"anyOf": [inner, {"type": "array", "items": {"type": "string"}}]}
        return inner


def schema(model, title: str) -> str:
    body = model.model_json_schema(by_alias=True, mode="validation", schema_generator=FileSchema)
    body = {"$schema": "https://json-schema.org/draft/2020-12/schema", "title": title,
            "$comment": "Generated by scripts/authoring/gen_json_schemas.py from the runtime's pydantic model. Do not edit.",
            **{k: v for k, v in body.items() if k != "title"}}
    return json.dumps(body, indent=2, ensure_ascii=False) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    stale = []
    for name, (model, title) in SCHEMAS.items():
        path = OUT / f"{name}.schema.json"
        text = schema(model, title)
        if args.check:
            if not path.exists() or path.read_text(encoding="utf-8") != text:
                stale.append(path.name)
        else:
            OUT.mkdir(exist_ok=True)
            path.write_text(text, encoding="utf-8", newline="\n")
    if stale:
        print("Stale schemas (run scripts/authoring/gen_json_schemas.py):", ", ".join(stale))
        return 1
    print(f"{len(SCHEMAS)} schemas {'up to date' if args.check else 'written'}.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
