"""Generate content/exercise-packs/zilla-v1: the 52 ZillaCode problems as a semantic pack.

Source: CodeDELeet's normalized import of ZillaCode (Apache-2.0), `public/packs/v3-zilla.json`, with its provenance
ledger and license. Set CODEDELEET to the CodeDELeet checkout (default D:/PROJ/CodeDELeet). The private ZillaCode
archive is never read and the reference application is never run.

The problems are specs in scripts/authoring/zilla/ (our contract: tables and names in snake_case, output columns in
order, prompts, references per language, authored edge fixtures, mutants). ZillaCode's two tests become the visible and
hidden fixtures, with inputs renamed to the contract; every expected row is recomputed by running the Datapass SQL
reference on DuckDB. The generator then grades every variant's reference, starter and mutants through the real grader
(`datapass_runtime.exercises.grade`) and writes the zilla-v1 mutants into scripts/exercise_packs_smoke.py.

Run from the repository root:  PYTHONPATH=runtime python scripts/authoring/gen_zilla.py [--only 1,2,3]
Review every expected row it prints before committing.
"""
from __future__ import annotations

import copy
import hashlib
import importlib
import json
import os
import re
import sys
import tempfile
from pathlib import Path

import duckdb

ROOT = Path.cwd()
sys.path.insert(0, str(Path(__file__).resolve().parent))
from zilla.common import SPECS  # noqa: E402

CODEDELEET = Path(os.environ.get("CODEDELEET", "D:/PROJ/CodeDELeet"))
SOURCE_PACK = CODEDELEET / "public" / "packs" / "v3-zilla.json"
SOURCE_LEDGER = CODEDELEET / "docs" / "v3" / "ZILLA_IMPORT_PROVENANCE.json"
SOURCE_LICENSE = CODEDELEET / "licenses" / "ZillaCode-Apache-2.0.txt"
PACK = ROOT / "content" / "exercise-packs" / "zilla-v1"
SMOKE = ROOT / "scripts" / "exercise_packs_smoke.py"
UPSTREAM = "https://github.com/davidzajac1/zillacode"
LANGUAGES = ["sql", "snowflake", "python", "polars", "sparklab", "dbt-sql"]
MARK_START = "    # --- zilla-v1 (generated by scripts/authoring/gen_zilla.py from scripts/authoring/zilla/; do not edit here) ---\n"
MARK_END = "    # --- end zilla-v1 ---\n"
LANGUAGE_NOTES = {
    "sql": "SQL (DuckDB): `FROM <table>`.",
    "snowflake": "Snowflake SQL: `FROM <table>`; your query is translated to DuckDB (Snowflake SQL dialect translated to DuckDB, not Snowflake), and functions outside the supported subset are refused.",
    "python": "pandas: each table is a list of row dicts in a variable of the same name; the starter turns them into DataFrames and passes them to `etl`, whose DataFrame is displayed.",
    "polars": "Polars: the same, with `pl.DataFrame`.",
    "sparklab": "SparkLab: `spark.table(\"<table>\")`; the last DataFrame is the result (bounded PySpark subset, not Apache Spark).",
    "dbt-sql": "dbt: your model reads `{{ source('zilla', '<table>') }}` and is built as a table by the Datapass dbt emulation (not dbt Core).",
}


def load_specs(only: set[int] | None) -> list[dict]:
    for module in sorted((Path(__file__).resolve().parent / "zilla").glob("p*.py")):
        importlib.import_module(f"zilla.{module.stem}")
    specs = sorted(SPECS, key=lambda s: s["n"])
    numbers = [s["n"] for s in specs]
    assert len(numbers) == len(set(numbers)), numbers
    return [s for s in specs if only is None or s["n"] in only]


# ---------------------------------------------------------------------------------------------------------------------
# Fixtures


def convert(value, kind: str):
    if value is None:
        return None
    if kind == "DOUBLE" or kind.startswith("DECIMAL"):
        return float(value)
    if kind in ("INTEGER", "BIGINT"):
        assert float(value) == int(value), value
        return int(value)
    if kind == "BOOLEAN":
        return bool(value)
    return str(value)


def shape(spec: dict, tables: dict[str, list[dict]]) -> dict[str, list[dict]]:
    """Source-named tables -> the contract's tables, columns in declared order, values typed."""
    rename_tables = spec.get("rename_tables", {})
    rename = spec.get("rename", {})
    out = {}
    for source_name, source_rows in tables.items():
        name = rename_tables.get(source_name, source_name)
        declared = spec["tables"][name]
        out_rows = []
        for row in source_rows:
            renamed = {rename.get(k, k): v for k, v in row.items()}
            assert set(renamed) == set(declared), (spec["n"], name, sorted(renamed), list(declared))
            out_rows.append({c: convert(renamed[c], declared[c]) for c in declared})
        out[name] = out_rows
    assert set(out) == set(spec["tables"]), (spec["n"], sorted(out))
    for name, table_rows in out.items():
        assert table_rows, f"zilla {spec['n']}: table {name} is empty (pandas/Polars need at least one row)"
        for column in spec["tables"][name]:
            # Polars infers the Null dtype for an all-NULL column, which no string or number operation accepts.
            assert any(row[column] is not None for row in table_rows), f"zilla {spec['n']}: {name}.{column} is all NULL"
    return out


def literal(value, kind: str) -> str:
    if value is None:
        text = "NULL"
    elif isinstance(value, bool):
        text = "TRUE" if value else "FALSE"
    elif isinstance(value, (int, float)):
        text = repr(value)
    else:
        text = "'" + str(value).replace("'", "''") + "'"
    return f"CAST({text} AS {kind})"


def expected_rows(spec: dict, tables: dict[str, list[dict]]) -> tuple[list[str], list[dict]]:
    """Run the SQL reference on DuckDB over typed tables (the same typing as the grader's CTEs)."""
    from datapass_runtime.catalog import json_value
    con = duckdb.connect()
    try:
        for name, table_rows in tables.items():
            declared = spec["tables"][name]
            selects = [" SELECT " + ", ".join(f"{literal(row[c], t)} AS \"{c}\"" for c, t in declared.items())
                       for row in table_rows]
            con.execute(f'CREATE TABLE "{name}" AS' + " UNION ALL".join(selects))
        cursor = con.execute(spec["sql"])
        columns = [d[0] for d in cursor.description]
        result = [{c: json_value(v) for c, v in zip(columns, row)} for row in cursor.fetchall()]
    finally:
        con.close()
    return columns, result


def fixtures(spec: dict, source: dict) -> list[dict]:
    tests = source["v3"]["tests"]
    items = [("example", "visible", spec.get("visible") or tests[0]["input"], None if spec.get("visible") else tests[0]["expected"])]
    if spec.get("hidden", True) is not False:
        custom = isinstance(spec.get("hidden"), dict)
        items.append(("more-rows", "hidden", spec["hidden"] if custom else tests[1]["input"], None if custom else tests[1]["expected"]))
    for edge in spec.get("edges", []):
        items.append((edge["id"], edge.get("visibility", "edge"), edge["tables"], None))
    out = []
    for check, visibility, raw, zilla_count in items:
        tables = shape(spec, raw)
        columns, result = expected_rows(spec, tables)
        assert columns == spec["output"], (spec["n"], check, columns, spec["output"])
        assert len(result) <= 200
        out.append({"id": check, "visibility": visibility, "input_rows": [], "tables": tables, "expected": result,
                    "_zilla_count": zilla_count})
    return out


def compare_zilla(spec: dict, ours: list[dict], theirs: list[dict]) -> str:
    """Compare recomputed rows with ZillaCode's expected rows (review aid; our contract may differ on purpose)."""
    names = {**{v: k for k, v in spec.get("rename", {}).items()}, **spec.get("zilla_output", {})}
    def key(row: dict, mapping: dict) -> tuple:
        values = []
        for column in spec["output"]:
            value = row.get(mapping.get(column, column), "<missing>")
            values.append(round(float(value), 6) if isinstance(value, (int, float)) and not isinstance(value, bool) else value)
        return tuple(str(v) for v in values)
    mine = sorted(key(r, {}) for r in ours)
    zilla = sorted(key(r, names) for r in theirs)
    if mine == zilla:
        return "same rows"
    missing = [r for r in zilla if r not in mine][:2]
    extra = [r for r in mine if r not in zilla][:2]
    return f"DIFFERS: ZillaCode-only {missing} ours-only {extra}"


# ---------------------------------------------------------------------------------------------------------------------
# Sources per language


def python_source(spec: dict, body: str, module: str) -> str:
    frame = "pd.DataFrame" if module == "pandas" else "pl.DataFrame"
    header = "import pandas as pd\n" if module == "pandas" else "import polars as pl\n"
    call = ", ".join(f"{frame}({name})" for name in spec["tables"])
    return f"{header}\n{body.strip()}\n\n\ndisplay(etl({call}))\n"


def dbt_source(spec: dict) -> str:
    text = spec["dbt"]
    if text != "auto":
        return text
    text = spec["sql"]
    for name in spec["tables"]:
        text = re.sub(rf"\b(from|join)(\s+){name}\b", rf"\1\2{{{{ source('zilla', '{name}') }}}}", text, flags=re.I)
    return text


def solutions(spec: dict) -> dict[str, str]:
    out = {"sql": spec["sql"], "python": python_source(spec, spec["python"], "pandas"),
           "polars": python_source(spec, spec["polars"], "polars")}
    if spec.get("snowflake"):
        out["snowflake"] = spec["sql"] if spec["snowflake"] == "same" else spec["snowflake"]
    if spec.get("sparklab"):
        out["sparklab"] = spec["sparklab"]
    if spec.get("dbt"):
        out["dbt-sql"] = dbt_source(spec)
    return {language: out[language] for language in LANGUAGES if language in out}


def starters(spec: dict, languages: list[str]) -> dict[str, str]:
    names = list(spec["tables"])
    first = names[0]
    args = ", ".join(names)
    comment = "    # Transform the input DataFrames into the result described in the brief.\n"
    out = {
        "sql": f"-- Return: {', '.join(spec['output'])}\nSELECT *\nFROM {first}\n",
        "snowflake": f"-- Snowflake SQL. Return: {', '.join(spec['output'])}\nSELECT *\nFROM {first}\n",
        "python": python_source(spec, f"def etl({args}):\n{comment}    return {first}", "pandas"),
        "polars": python_source(spec, f"def etl({args}):\n{comment}    return {first}", "polars"),
        "sparklab": "from pyspark.sql import functions as F\nfrom pyspark.sql import Window\n\n"
                    + "".join(f"{n} = spark.table(\"{n}\")\n" for n in names) + f"{first}\n",
        "dbt-sql": f"select *\nfrom {{{{ source('zilla', '{first}') }}}}\n",
    }
    return {language: out[language] for language in languages}


def mutant_sources(spec: dict) -> dict[str, list[str]]:
    out = {}
    for language, items in spec.get("mutants", {}).items():
        if language in ("python", "polars"):
            items = [python_source(spec, body, "pandas" if language == "python" else "polars") for body in items]
        out[language] = items
    return out


# ---------------------------------------------------------------------------------------------------------------------
# Public scenario


def sections(spec: dict, languages: list[str], source: dict, upstream: list[str]) -> list[dict]:
    tables = "\n".join(f"{name}(" + ", ".join(f"{c} {t}" for c, t in cols.items()) + ")" for name, cols in spec["tables"].items())
    order = spec.get("order_text") or ("Row order is not graded." if not spec.get("ordered") else "")
    output = f"Columns in this order: {', '.join(spec['output'])}. {spec.get('grain', '')} {order}".replace("  ", " ").strip()
    changes = spec.get("changes", [])
    attribution = (f"Adapted from ZillaCode problem {spec['n']}, \"{source['title']}\" ({UPSTREAM}, Apache-2.0), through "
                   "CodeDELeet's normalized import. " + ("Datapass changes: " + " ".join(changes) if changes else
                                                          "Datapass kept the ZillaCode contract; expected rows were recomputed."))
    return [
        {"title": "Tables", "body": tables},
        {"title": "How each engine reads the tables", "body": " ".join(LANGUAGE_NOTES[l] for l in languages)},
        {"title": "Output", "body": output},
        {"title": "Common pitfall", "body": spec["pitfall"]},
        {"title": "Source", "body": attribution},
    ]


def paragraph(text: str) -> str:
    return " ".join(text.split())


def scenario(spec: dict, source: dict, ledger: dict, fixture_set: list[dict], sols: dict[str, str]) -> tuple[dict, dict]:
    sid = f"zilla-{spec['n']:03d}-{spec['slug']}"
    languages = list(sols)
    upstream = ledger.get(source["id"], [])
    visible = fixture_set[0]
    common = {
        "schema_version": 1,
        "title": spec["title"],
        "difficulty": spec["difficulty"],
        "topics": spec["topics"],
        "tags": ["zillacode", "leetcode-style", "shared-fixture"],
        "origin": "migrated",
        "prompt": paragraph(spec["prompt"]),
        "sections": sections(spec, languages, source, upstream),
        "fixtures": [{"id": sid + "-fixtures", "version": "1"}],
        "visible_checks": [{"id": "example", "description": "Public example: ZillaCode's first test, the tables shown above."}],
        "hidden_check_refs": [f["id"] for f in fixture_set if f["visibility"] == "hidden"],
        "edge_check_refs": [f["id"] for f in fixture_set if f["visibility"] == "edge"],
        "hints": spec["hints"],
        "solution": {"available": True, "reveal": "explicit"},
        "explanation": paragraph(spec["explanation"]),
        "follow_ups": [spec.get("reflection", "Which rows would change the answer at scale: duplicates, NULL keys or ties?")],
        "canonical_placement": {"domain": "data-engineering", "topic": spec["topics"][0]},
        "related_associations": [f"zillacode/{spec['n']}"],
        "recommendation": {"rank": spec["n"], "reason": "ZillaCode problem order"},
        "validator_version": "semantic-rows-v1",
        "validation": {
            "kind": "rows", "ordered": bool(spec.get("ordered")), "duplicate_sensitive": True,
            "relative_tolerance": 1e-09, "absolute_tolerance": 1e-06,
            "required_columns": spec["output"], "exact_schema": spec["output"], "forbidden_extra_columns": True,
            "null_semantics": "equal",
        },
        "data_context": [{"name": name, "columns": cols, "sample_rows": visible["tables"][name]}
                         for name, cols in spec["tables"].items()],
        "output_schema": {c: "value" for c in spec["output"]},
        "runtime_requirements": [],
        "provenance": {
            "source": f"ZillaCode problem {spec['n']} \"{source['title']}\" ({UPSTREAM}), from CodeDELeet's normalized import {source['id']}",
            "license": "Apache-2.0; see LICENSE and NOTICE in content/exercise-packs/zilla-v1",
            "upstream_changes": " ".join(upstream) or "none recorded",
            "datapass_changes": " ".join(spec.get("changes", [])) or "Contract kept; names already snake_case.",
            "fixtures": "Visible: ZillaCode test 1. Hidden: ZillaCode test 2 unless noted. Edge: authored for Datapass. "
                        "Expected rows recomputed from the Datapass SQL reference on DuckDB and reviewed by hand; "
                        "every variant is graded in CI.",
        },
        "constraints": {"fixtures": "At most 200 rows per table; complete results are graded, truncated results never pass."},
    }
    ops = spec.get("ops", spec["topics"])
    variants = {}
    for language, starter in starters(spec, languages).items():
        variants[language] = {"starter_source": starter, "supported_operations": ops}
        if language == "dbt-sql":
            variants[language]["model"] = spec.get("dbt_model", spec["slug"].replace("-", "_"))
    semantic = {
        "id": sid, "version": "1", "industry": spec.get("industry", "ZillaCode data transformations"),
        "learning_objectives": spec.get("objectives", spec["hints"][:2]),
        "optimization": spec.get("optimization", spec["explanation"].strip().split("\n")[0]),
        "reflection": common["follow_ups"][0],
    }
    return ({"semantic": semantic, "fixture_version": "1", "common": common, "variants": variants},
            {"solutions": sols, "fixtures": fixture_set})


# ---------------------------------------------------------------------------------------------------------------------
# Checks through the real grader


def grade_all(scenarios: list[dict], mutants: dict[str, list[str]]) -> list[str]:
    from datapass_runtime.execution import Engine
    from datapass_runtime import exercises
    problems: list[str] = []
    with tempfile.TemporaryDirectory(prefix="datapass-zilla-gen-") as folder:
        engine = Engine(Path(folder), "duckdb", trusted_python=True)
        try:
            for item in scenarios:
                for language, variant in item["variants"].items():
                    ident = f"{item['semantic']['id']}-{language}"
                    spec = exercises.definition(ident)

                    def run(code: str) -> dict:
                        return exercises.grade(engine, {
                            "exercise_id": ident, "exercise_version": spec["version"], "language": language,
                            "code": code, "mode": "submit", "notebook_id": "zilla-gen", "cell_id": "solution",
                            "source_revision": 1, "profile": "generic_8x8", "aqe": True})

                    def summary(result: dict) -> str:
                        return "; ".join(f"{c['id']}={c['status']}" + ("" if c["passed"] else f" ({c['message'][:160]})")
                                         for c in result["checks"])

                    reference = run(exercises.solution(ident)["source"])
                    if reference["status"] != "passed":
                        problems.append(f"{ident}: reference {reference['status']}: {summary(reference)}")
                    starter = run(variant["starter_source"])
                    if starter["status"] == "passed":
                        problems.append(f"{ident}: starter passes")
                    elif any(c["execution_status"] != "success" for c in starter["checks"]):
                        problems.append(f"{ident}: starter does not run: {summary(starter)}")
                    for index, mutant in enumerate(mutants.get(ident, [])):
                        graded = run(mutant)
                        if graded["status"] == "passed":
                            problems.append(f"{ident}: mutant #{index} passes")
                        elif any(c["execution_status"] != "success" for c in graded["checks"]):
                            problems.append(f"{ident}: mutant #{index} does not run: {summary(graded)}")
        finally:
            engine.catalog.close()
    return problems


def write_mutants(mutants: dict[str, list[str]]) -> None:
    text = SMOKE.read_text(encoding="utf-8")
    block = MARK_START + "".join(
        f"    {json.dumps(ident)}: [\n" + "".join(f"        {json.dumps(m, ensure_ascii=False)},\n" for m in items) + "    ],\n"
        for ident, items in sorted(mutants.items())) + MARK_END
    if MARK_START in text:
        start = text.index(MARK_START)
        end = text.index(MARK_END) + len(MARK_END)
        text = text[:start] + block + text[end:]
    else:
        anchor = "\n}\n\n\ndef grade("
        assert anchor in text
        text = text.replace(anchor, "\n" + block.rstrip("\n") + "\n}\n\n\ndef grade(", 1)
    SMOKE.write_text(text, encoding="utf-8", newline="\n")


NOTICE = """zilla-v1: ZillaCode problems adapted for Datapass Workbench

This pack contains material adapted from ZillaCode ({upstream}), an open-source
collection of data engineering practice problems by David Zajac and contributors,
licensed under the Apache License, Version 2.0 (see LICENSE in this folder).

Adapted material: the problem statements (rewritten), the input fixtures of the two
tests of each problem, and the reference transformations the Datapass references were
derived from. It reached Datapass through CodeDELeet's normalized import
(public/packs/v3-zilla.json, SHA-256 {pack_sha}; provenance ledger
docs/v3/ZILLA_IMPORT_PROVENANCE.json, SHA-256 {ledger_sha}). The private ZillaCode
archive was not used and the reference application was not run.

Modifications (see each exercise's "Source" section and provenance):
- statements rewritten for Datapass; table and column names normalized to snake_case;
- output contracts made explicit (column order, row order, NULL and tie rules), with
  documented corrections where the original statement and reference disagreed;
- references rewritten for DuckDB SQL, Snowflake SQL (translated to DuckDB), pandas,
  Polars, SparkLab and the Datapass dbt emulation;
- expected rows recomputed by running the Datapass references; hidden and edge
  fixtures added for ties, NULLs and empty groups.

The Datapass-authored parts of this pack are part of the Datapass Workbench repository.
"""


def main() -> None:
    only = None
    if "--only" in sys.argv:
        only = {int(x) for x in sys.argv[sys.argv.index("--only") + 1].split(",")}
    source_pack = json.loads(SOURCE_PACK.read_text(encoding="utf-8"))
    by_number = {int(q["id"].split("-")[1]): q for q in source_pack["questions"]}
    ledger = {p["id"]: p["changes"] for p in json.loads(SOURCE_LEDGER.read_text(encoding="utf-8"))["problems"]}
    specs = load_specs(only)
    scenarios, grading, mutants = [], {}, {}
    for spec in specs:
        source = by_number[spec["n"]]
        fixture_set = fixtures(spec, source)
        counts = {f["id"]: f.pop("_zilla_count") for f in fixture_set}
        public, private = scenario(spec, source, ledger, fixture_set, solutions(spec))
        scenarios.append(public)
        grading[public["semantic"]["id"]] = private
        for language, items in mutant_sources(spec).items():
            assert language in public["variants"], (spec["n"], language)
            mutants[f"{public['semantic']['id']}-{language}"] = items
        print(f"\n=== {public['semantic']['id']} ({', '.join(public['variants'])})")
        for f in fixture_set:
            zilla = counts[f["id"]]
            flag = "" if zilla is None else f" (ZillaCode: {len(zilla)} rows, {compare_zilla(spec, f['expected'], zilla)})"
            print(f"  [{f['visibility']}] {f['id']}: {len(f['expected'])} rows{flag}")
            for row in f["expected"]:
                print("     ", json.dumps(row, ensure_ascii=False))
    manifest = {
        "schema_version": 1, "id": "zilla-v1", "version": "1",
        "title": "ZillaCode problems: one result contract in DuckDB SQL, Snowflake SQL, pandas, Polars, SparkLab and dbt",
        "enabled": True,
        "provenance": {
            "source": f"ZillaCode ({UPSTREAM}), Apache-2.0, through CodeDELeet's normalized import v3-zilla.json",
            "source_sha256": hashlib.sha256(SOURCE_PACK.read_bytes()).hexdigest(),
            "ledger_sha256": hashlib.sha256(SOURCE_LEDGER.read_bytes()).hexdigest(),
            "license": "Apache-2.0 (LICENSE, NOTICE)",
        },
    }
    if only is None:
        PACK.mkdir(parents=True, exist_ok=True)
        (PACK / "manifest.json").write_text(json.dumps(manifest, indent=2, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")
        (PACK / "scenarios.json").write_text(json.dumps(scenarios, indent=1, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")
        (PACK / "grading.server.json").write_text(json.dumps(grading, indent=1, ensure_ascii=False) + "\n", encoding="utf-8", newline="\n")
        (PACK / "LICENSE").write_text(SOURCE_LICENSE.read_text(encoding="utf-8"), encoding="utf-8", newline="\n")
        (PACK / "NOTICE").write_text(NOTICE.format(upstream=UPSTREAM, pack_sha=manifest["provenance"]["source_sha256"],
                                                   ledger_sha=manifest["provenance"]["ledger_sha256"]), encoding="utf-8", newline="\n")
        write_mutants(mutants)
    else:
        # Partial runs check the selected problems in a temporary content root and write nothing.
        root = Path(tempfile.mkdtemp(prefix="datapass-zilla-content-"))
        target = root / "exercise-packs" / "zilla-v1"
        target.mkdir(parents=True)
        (target / "manifest.json").write_text(json.dumps(manifest), encoding="utf-8", newline="\n")
        (target / "scenarios.json").write_text(json.dumps(scenarios), encoding="utf-8", newline="\n")
        (target / "grading.server.json").write_text(json.dumps(grading), encoding="utf-8", newline="\n")
        os.environ["DATAPASS_CONTENT_ROOT"] = str(root)
    problems = grade_all(scenarios, mutants)
    print("\nPROBLEMS:\n  " + "\n  ".join(problems) if problems else "\nAll references pass; starters and mutants run and fail.")
    print(f"{len(scenarios)} scenarios, {sum(len(s['variants']) for s in scenarios)} variants, "
          f"{sum(len(m) for m in mutants.values())} mutants.")


if __name__ == "__main__":
    main()
