export const cheatSheets = [
  {
    id: 'python', label: 'Python', icon: 'PY', subtitle: 'ETL, APIs, files and interview syntax', language: 'python', practiceTarget: 'Python',
    useFor: ['ETL control flow', 'APIs and files', 'small reusable utilities', 'interview coding'],
    sections: [
      ['Collections + control flow', 'rows = [{"id": 1}, {"id": 2}]\nids = {row["id"] for row in rows}\n\nfor row in rows:\n    if row["id"] in ids:\n        print(row["id"])'],
      ['Functions', 'def qualified_name(schema: str, table: str) -> str:\n    return f"{schema}.{table}"\n\nname = qualified_name("dbo", "orders")'],
      ['Files + JSON', 'from pathlib import Path\nimport json\n\nconfig = json.loads(Path("config.json").read_text())\nfiles = list(Path("landing").glob("*.json"))'],
      ['Safe parsing', 'try:\n    value = int(raw_value)\nexcept ValueError:\n    value = None'],
    ],
    mentalModels: ['list = ordered sequence; dict = key → value; set = uniqueness / fast membership', 'Prefer small functions with explicit inputs and return values.', 'Use Python loops for control-plane work; use DataFrame/SQL engines for large row-level transformations.'],
    interview: ['mutable vs immutable types', 'list/dict/set comprehensions', '*args, **kwargs, lambda, enumerate, zip, generators', 'average O(1) dict/set lookup vs O(n) list scan'],
    starter: 'from pathlib import Path\n\ndef load_paths(folder: str):\n    """Return all parquet files in deterministic order."""\n    # Try it here\n    pass\n',
  },
  {
    id: 'pandas', label: 'NumPy + pandas', icon: 'PD', subtitle: 'Vectorized local DataFrame work', language: 'python', practiceTarget: 'Pandas',
    useFor: ['local analytics', 'data cleaning', 'transformation prototypes', 'small/medium datasets'],
    sections: [
      ['Select + filter + assign', 'result = (\n    df.loc[df["status"].eq("ACTIVE"), ["customer_id", "amount"]]\n      .assign(amount_eur=lambda x: x["amount"] * 0.92)\n)'],
      ['Group + aggregate', 'summary = (\n    df.groupby("customer_id", as_index=False)\n      .agg(total=("amount", "sum"), rows=("amount", "size"))\n)'],
      ['Join + dedupe', 'result = orders.merge(customers, on="customer_id", how="left")\nlatest = history.sort_values("updated_at").drop_duplicates("customer_id", keep="last")'],
      ['NumPy vectorization', 'import numpy as np\n\ndf["band"] = np.select(\n    [df["amount"] >= 1000, df["amount"] >= 100],\n    ["high", "medium"],\n    default="low",\n)'],
    ],
    mentalModels: ['Think column operations first, Python loops last.', 'pandas aligns Series by index, not only by position.', 'Check shape, dtypes and nulls before debugging values.'],
    interview: ['loc vs iloc', 'merge vs concat', 'groupby + agg', 'drop_duplicates + sort_values', 'isna/fillna/astype', 'vectorization vs iterrows'],
    starter: 'import pandas as pd\n\ndf = pd.DataFrame({"customer_id": [1, 1, 2], "amount": [10, 30, 20]})\n\n# Build a customer-level total\n',
  },
  {
    id: 'pyspark', label: 'PySpark', icon: 'SP', subtitle: 'Distributed DataFrame transformations', language: 'python', practiceTarget: 'Spark',
    useFor: ['large-scale ETL', 'Databricks / Fabric Spark', 'distributed joins', 'lakehouse pipelines'],
    sections: [
      ['Core transformations', 'from pyspark.sql import functions as F\n\nresult = (\n    df.filter(F.col("status") == "ACTIVE")\n      .select("customer_id", "amount")\n      .withColumn("amount_eur", F.col("amount") * F.lit(0.92))\n)'],
      ['Aggregate + join', 'summary = df.groupBy("customer_id").agg(F.sum("amount").alias("total"))\nresult = summary.join(customers, "customer_id", "left")'],
      ['Window', 'from pyspark.sql.window import Window\n\nw = Window.partitionBy("customer_id").orderBy(F.col("updated_at").desc())\nlatest = df.withColumn("rn", F.row_number().over(w)).filter("rn = 1")'],
      ['Write Delta', '(result.write\n    .format("delta")\n    .mode("overwrite")\n    .partitionBy("load_date")\n    .saveAsTable("silver.sales"))'],
    ],
    mentalModels: ['Transformations are lazy; actions trigger execution.', 'groupBy, join, distinct and orderBy can shuffle.', 'Partitions are units of parallelism; avoid collect() for large data.'],
    interview: ['transformations vs actions', 'narrow vs wide', 'shuffle causes', 'broadcast join', 'repartition vs coalesce', 'cache/persist', 'small-file problem'],
    starter: 'from pyspark.sql import functions as F\n\n# df: customer_id, amount, status\nresult = (\n    df\n    # Filter ACTIVE rows and aggregate total amount per customer\n)\n',
  },
  {
    id: 'sql', label: 'SQL + T-SQL', icon: 'SQL', subtitle: 'Warehouse querying and transformations', language: 'sql', practiceTarget: 'T-SQL',
    useFor: ['warehouse transformations', 'data modeling', 'quality checks', 'interview queries'],
    sections: [
      ['Logical query flow', 'SELECT customer_id, SUM(amount) AS total\nFROM dbo.sales\nWHERE status = \'ACTIVE\'\nGROUP BY customer_id\nHAVING SUM(amount) > 1000\nORDER BY total DESC;'],
      ['CTE + window', 'WITH ranked AS (\n    SELECT *, ROW_NUMBER() OVER (\n        PARTITION BY customer_id ORDER BY updated_at DESC\n    ) AS rn\n    FROM dbo.customer_history\n)\nSELECT * FROM ranked WHERE rn = 1;'],
      ['Conditional aggregation', 'SELECT customer_id,\n       SUM(CASE WHEN status = \'PAID\' THEN amount ELSE 0 END) AS paid_amount\nFROM dbo.orders\nGROUP BY customer_id;'],
      ['T-SQL transaction', 'BEGIN TRY\n    BEGIN TRAN;\n    -- DML\n    COMMIT;\nEND TRY\nBEGIN CATCH\n    IF @@TRANCOUNT > 0 ROLLBACK;\n    THROW;\nEND CATCH;'],
    ],
    mentalModels: ['SQL is declarative: describe the result, let the optimizer choose the physical plan.', 'Know the grain before joining or aggregating.', 'Window functions preserve row grain; GROUP BY changes row grain.'],
    interview: ['INNER vs LEFT join', 'WHERE vs HAVING', 'ROW_NUMBER/RANK/DENSE_RANK', 'ROWS vs RANGE', 'CTE vs temp table', 'PK/FK/indexes', 'SCD Type 2', 'NULL semantics'],
    starter: 'WITH ranked AS (\n    SELECT customer_id, updated_at,\n           -- add row_number here\n    FROM dbo.customer_history\n)\nSELECT * FROM ranked\n-- keep latest row per customer\n',
  },
  {
    id: 'powershell', label: 'PowerShell', icon: 'PS', subtitle: 'Windows automation and operations', language: 'powershell', practiceTarget: 'PowerShell',
    useFor: ['Windows VM administration', 'file automation', 'REST APIs', 'service/process inspection'],
    sections: [
      ['Pipeline + objects', 'Get-ChildItem C:\\ETL -File |\n  Where-Object Length -gt 1MB |\n  Select-Object Name, Length'],
      ['Loop', '$tables = @("customers", "orders")\nforeach ($table in $tables) {\n    Write-Host "Loading $table"\n}'],
      ['REST API', '$headers = @{ Authorization = "Bearer $env:API_TOKEN" }\n$response = Invoke-RestMethod -Uri $uri -Headers $headers -Method Get'],
      ['Operational checks', 'Get-Service | Where-Object Status -eq "Running"\nGet-Process | Sort-Object CPU -Descending | Select-Object -First 10\nTest-NetConnection server -Port 1433'],
    ],
    mentalModels: ['PowerShell pipelines carry .NET objects, not plain text by default.', 'Verb-Noun naming makes commands discoverable.', 'Prefer explicit error handling and non-interactive authentication in automation.'],
    interview: ['Where-Object vs ForEach-Object', '$env: variables', 'Invoke-RestMethod', 'services/processes', 'Get-Command/Get-Help'],
    starter: '$folder = "C:\\ETL"\n\n# List CSV files larger than 1 MB and select Name + Length\n',
  },
  {
    id: 'csharp-functions', label: 'C# · Azure Functions', icon: 'C#', subtitle: 'Serverless .NET data utilities', language: 'csharp', practiceTarget: 'C# / TE',
    useFor: ['HTTP/event functions', 'small ingestion APIs', 'queue processing', 'integration utilities'],
    sections: [
      ['Async method', 'public async Task<string> LoadAsync(string table)\n{\n    await _loader.RunAsync(table);\n    return "done";\n}'],
      ['Function shape', '[Function("IngestOrders")]\npublic async Task<HttpResponseData> Run(\n    [HttpTrigger(AuthorizationLevel.Function, "post")] HttpRequestData req)\n{\n    var response = req.CreateResponse(HttpStatusCode.Accepted);\n    return response;\n}'],
      ['LINQ', 'var activeIds = rows\n    .Where(x => x.Status == "ACTIVE")\n    .Select(x => x.CustomerId)\n    .Distinct()\n    .ToList();'],
      ['Configuration', 'var endpoint = configuration["ApiEndpoint"]\n    ?? throw new InvalidOperationException("ApiEndpoint missing");'],
    ],
    mentalModels: ['Task/async represents asynchronous work; avoid blocking with .Result/.Wait().', 'Functions are event handlers: trigger in, small unit of work, observable outcome.', 'Keep growing business logic outside the function entry point.'],
    interview: ['value vs reference types', 'IEnumerable/LINQ', 'async/await', 'dependency injection', 'JSON serialization', 'configuration/secrets', 'HTTP vs queue triggers'],
    starter: 'public async Task<int> CountActiveAsync(IEnumerable<Row> rows)\n{\n    // Return the number of ACTIVE rows\n    return 0;\n}\n',
  },
  {
    id: 'csharp-tabular', label: 'C# · Tabular Editor', icon: 'TE', subtitle: 'Automate Power BI semantic models', language: 'csharp', practiceTarget: 'C# / TE',
    useFor: ['bulk measure edits', 'display folders', 'format strings', 'semantic-model automation'],
    sections: [
      ['Selected measures', 'foreach (var measure in Selected.Measures)\n{\n    measure.DisplayFolder = "KPIs";\n}'],
      ['LINQ filter', 'var marginMeasures = Model.AllMeasures\n    .Where(m => m.Name.Contains("Margin"));'],
      ['Create measure', 'var table = Model.Tables["Sales"];\nvar measure = table.AddMeasure("Total Sales", "SUM(Sales[Amount])", "KPIs");'],
      ['Annotations', 'foreach (var measure in Model.AllMeasures)\n{\n    measure.SetAnnotation("Owner", "BI Team");\n}'],
    ],
    mentalModels: ['Tabular Editor scripts mutate semantic-model metadata, not report visuals.', 'Selected.* targets selected objects; Model.* traverses the full model.', 'Test bulk scripts on a copy/version-controlled model.'],
    interview: ['foreach + var', 'LINQ Where/Select', 'Model.Tables / AllMeasures', 'Selected.Measures', 'format strings/display folders', 'metadata vs DAX evaluation'],
    starter: '// Put selected measures into a folder named "Review"\nforeach (var measure in Selected.Measures)\n{\n    // edit the measure\n}\n',
  },
  {
    id: 'airflow', label: 'Airflow', icon: 'AF', subtitle: 'DAG scheduling and orchestration', language: 'python', practiceTarget: 'Airflow',
    useFor: ['pipeline scheduling', 'task dependencies', 'retries', 'backfills and orchestration'],
    sections: [
      ['TaskFlow DAG', 'from airflow.decorators import dag, task\nfrom datetime import datetime\n\n@dag(schedule="0 6 * * *", start_date=datetime(2026, 1, 1), catchup=False)\ndef sales_pipeline():\n    @task(retries=2)\n    def extract():\n        return "landing/sales"\n    extract()\n\nsales_pipeline()'],
      ['Dependencies', 'extract >> transform >> load\n\nextract >> [customers, orders]\n[customers, orders] >> publish'],
      ['Idempotent task', '@task\ndef load_partition(ds=None):\n    target = f"sales/load_date={ds}"\n    overwrite_partition(target)'],
      ['Data boundary', '# XCom: small metadata, IDs, paths\n# Object storage/table: actual datasets\npath = extract()\ntransform(path)'],
    ],
    mentalModels: ['A DAG models dependencies, not the data itself.', 'Tasks should be retry-safe and ideally idempotent.', 'Pass small metadata through orchestration; store real datasets in data systems.'],
    interview: ['DAG vs task', 'schedule/start_date/catchup', 'retries', 'XCom boundaries', 'sensors', 'backfill', 'idempotency', 'topological ordering'],
    starter: 'from airflow.decorators import dag, task\n\n# Build extract -> transform -> load with retries on load\n',
  },
  {
    id: 'dax', label: 'DAX', icon: 'DX', subtitle: 'Power BI measures and filter context', language: 'plaintext', practiceTarget: 'DAX',
    useFor: ['semantic-model measures', 'business KPIs', 'filter context', 'Power BI reporting'],
    sections: [
      ['Measure', 'Total Sales =\nSUM(Sales[Amount])'],
      ['CALCULATE', 'Active Sales =\nCALCULATE(\n    [Total Sales],\n    Customer[Status] = "ACTIVE"\n)'],
      ['Iterator', 'Gross Margin =\nSUMX(\n    Sales,\n    Sales[Revenue] - Sales[Cost]\n)'],
      ['Safe division', 'Margin % =\nDIVIDE([Gross Margin], [Total Sales])'],
    ],
    mentalModels: ['Measures are evaluated in filter context.', 'CALCULATE modifies filter context.', 'X-functions iterate a table expression and evaluate row by row.'],
    interview: ['measure vs calculated column', 'row vs filter context', 'CALCULATE', 'SUMX/FILTER', 'ALL/REMOVEFILTERS', 'DIVIDE', 'context transition'],
    starter: 'Revenue % =\nVAR Revenue = [Total Sales]\nRETURN\n    // divide by total sales ignoring product filters\n',
  },
  {
    id: 'kubernetes', label: 'Kubernetes', icon: 'K8', subtitle: 'Inspect and troubleshoot deployed data services', language: 'yaml', practiceTarget: 'K8s',
    useFor: ['inspect pods', 'read logs', 'deployment troubleshooting', 'config/service concepts'],
    sections: [
      ['Inspect', 'kubectl get pods -n data\nkubectl describe pod <pod> -n data\nkubectl logs <pod> -n data --tail=100'],
      ['Deployment basics', 'apiVersion: apps/v1\nkind: Deployment\nmetadata:\n  name: api\nspec:\n  replicas: 2\n  selector:\n    matchLabels:\n      app: api'],
      ['Service idea', 'apiVersion: v1\nkind: Service\nmetadata:\n  name: api\nspec:\n  selector:\n    app: api\n  ports:\n    - port: 80\n      targetPort: 8000'],
      ['Useful commands', 'kubectl config current-context\nkubectl get events -n data --sort-by=.lastTimestamp\nkubectl rollout status deployment/api -n data'],
    ],
    mentalModels: ['Pod = running unit; Deployment = desired replicated pods; Service = stable network endpoint.', 'Namespace scopes names/resources.', 'Start troubleshooting with status, events, describe and logs.'],
    interview: ['pod vs deployment vs service', 'config map vs secret', 'readiness vs liveness', 'requests/limits', 'namespace/context', 'kubectl logs/describe'],
    starter: '# Write a small Deployment for an API container on port 8000\n',
  },
]

export const cheatSheetById = Object.fromEntries(cheatSheets.map((sheet) => [sheet.id, sheet]))
