export const tracks = [
  {
    id: 'foundations',
    name: 'Programming Foundations',
    short: 'Start here',
    icon: '01',
    description: 'Variables, types, collections, conditions, loops, functions, arguments, return values, errors, and Big-O intuition.',
    concepts: ['variables & types', 'list / array', 'dict / map', 'set', 'if / elif / else', 'for / while', 'functions', 'arguments', 'return', 'scope', 'exceptions', 'Big-O basics'],
  },
  {
    id: 'algorithms',
    name: 'Algorithms + Data Structures',
    short: 'Algorithms',
    icon: 'AL',
    description: 'Practical algorithm patterns for interviews: searching, counting, deduplicating, batching, stacks/queues, and complexity intuition.',
    concepts: ['linear search', 'hash lookup', 'frequency map', 'dedupe', 'stack / queue', 'batching', 'binary search', 'nested loop vs lookup'],
  },
  {
    id: 'python',
    name: 'Python for Data Engineering',
    short: 'Python',
    icon: 'PY',
    description: 'Practical Python syntax used in ETL jobs, APIs, files, configuration, transformations, and interviews.',
    concepts: ['imports', 'enumerate / zip', 'comprehensions', 'sorting', 'files', 'pathlib', 'JSON', 'datetime', 'type hints', 'classes lightly'],
  },
  {
    id: 'pandas',
    name: 'Pandas + NumPy',
    short: 'Pandas',
    icon: 'PD',
    description: 'DataFrame manipulation patterns you should be able to write without copying from a book.',
    concepts: ['DataFrame', 'select', 'filter', 'assign', 'groupby', 'merge', 'nulls', 'datetime', 'dedupe', 'NumPy arrays', 'vectorization'],
  },
  {
    id: 'sql',
    name: 'SQL / T-SQL',
    short: 'T-SQL',
    icon: 'SQL',
    description: 'Core SQL plus Microsoft-flavored T-SQL patterns for data engineering interviews and warehouse work.',
    concepts: ['SELECT', 'WHERE', 'JOIN', 'GROUP BY', 'HAVING', 'CASE', 'CTE', 'window functions', 'dedupe', 'SCD Type 2', 'PK / FK', 'transactions'],
  },
  {
    id: 'pyspark',
    name: 'PySpark',
    short: 'Spark',
    icon: 'SP',
    description: 'DataFrame transformations, joins, windows, partitions, and writes in the syntax used on Databricks and Fabric Spark.',
    concepts: ['SparkSession', 'read', 'select', 'filter', 'withColumn', 'groupBy', 'join', 'Window', 'write', 'partitions', 'shuffle intuition'],
  },
  {
    id: 'dax',
    name: 'DAX',
    short: 'DAX',
    icon: 'DX',
    description: 'Measures, variables, filter context, iterators, and the formulas that matter most for Power BI work.',
    concepts: ['measure', 'VAR / RETURN', 'CALCULATE', 'filter context', 'SUMX', 'FILTER', 'DIVIDE', 'COUNTROWS', 'time patterns'],
  },
  {
    id: 'csharp',
    name: 'C# for Tabular Editor',
    short: 'C# / TE',
    icon: 'C#',
    description: 'Enough C# and LINQ to read and write useful Tabular Editor scripts without trying to become a .NET application developer.',
    concepts: ['var', 'string', 'if', 'foreach', 'collections', 'lambda', 'LINQ', 'Model', 'Selected', 'measures', 'display folders'],
  },
  {
    id: 'airflow',
    name: 'Airflow',
    short: 'Airflow',
    icon: 'AF',
    description: 'DAG authoring syntax, dependencies, schedules, retries, task boundaries, and orchestration mental models.',
    concepts: ['DAG', '@task', 'dependencies', 'schedule', 'retries', 'idempotency', 'XCom boundaries', 'backfill intuition'],
  },
  {
    id: 'bash',
    name: 'Bash + SSH + Linux VM',
    short: 'Bash / VM',
    icon: '>_',
    description: 'Navigate a Linux machine, inspect files and processes, move data, connect over SSH, and run an ETL script safely.',
    concepts: ['pwd / ls / cd', 'mkdir / cp / mv / rm', 'cat / head / tail', 'grep / find', 'pipes', 'env vars', 'chmod', 'ssh', 'scp', 'processes'],
  },
  {
    id: 'powershell',
    name: 'PowerShell',
    short: 'PowerShell',
    icon: 'PS',
    description: 'Windows terminal literacy for services, files, environment variables, APIs, and VM administration.',
    concepts: ['Get-ChildItem', 'Get-Content', 'Where-Object', 'ForEach-Object', 'services', 'environment', 'Invoke-RestMethod', 'Test-NetConnection'],
  },
  {
    id: 'git',
    name: 'Git',
    short: 'Git',
    icon: 'GT',
    description: 'The commands you should know to work safely in a repo: inspect, stage, commit, branch, sync, and recover.',
    concepts: ['status', 'diff', 'add', 'commit', 'branch', 'switch', 'pull', 'push', 'restore', 'log', '.gitignore'],
  },
  {
    id: 'cron',
    name: 'cron + Scheduling',
    short: 'cron',
    icon: 'CR',
    description: 'Classic Linux scheduling syntax, logs, paths, and the common production mistakes around environment and idempotency.',
    concepts: ['crontab', '5 fields', 'absolute paths', 'stdout/stderr', 'environment', 'idempotent jobs'],
  },
  {
    id: 'docker',
    name: 'Docker',
    short: 'Docker',
    icon: 'DK',
    description: 'Images, containers, Dockerfiles, volumes, ports, environment variables, and the commands a data engineer sees daily.',
    concepts: ['image vs container', 'Dockerfile', 'build', 'run', 'ps', 'logs', 'exec', 'volume', 'port', 'env var'],
  },
  {
    id: 'kubernetes',
    name: 'Kubernetes',
    short: 'K8s',
    icon: 'K8',
    description: 'Enough Kubernetes to inspect and troubleshoot a deployed data service without becoming a cluster administrator.',
    concepts: ['pod', 'deployment', 'service', 'namespace', 'kubectl get', 'describe', 'logs', 'apply', 'context', 'config map / secret idea'],
  },
  {
    id: 'cloud',
    name: 'Azure + GCP + Fabric CLI',
    short: 'Cloud CLI',
    icon: 'CL',
    description: 'Authentication, context, listing resources, and command-family recognition for Azure, Google Cloud, and Microsoft Fabric.',
    concepts: ['az login', 'subscription', 'gcloud auth', 'project', 'fab auth', 'workspace listing', 'safe automation identities'],
  },
  {
    id: 'gateway',
    name: 'Power BI Gateway on a VM',
    short: 'Gateway',
    icon: 'GW',
    description: 'A practical operator checklist for understanding where the gateway runs, how it connects, and what you inspect when refreshes fail.',
    concepts: ['Windows VM', 'standard gateway', 'service account', 'outbound connectivity', 'drivers', 'data source mapping', 'logs', 'high availability'],
  },
]

const L = (x) => x

export const lessons = [
  // FOUNDATIONS
  L({
    id: 'f-variables', track: 'foundations', level: 'Beginner', language: 'python', title: 'Variables and basic types',
    concept: 'A variable is a name pointing to a value. Python infers the type from the value you assign.',
    why: 'Every later skill—DataFrames, loops, functions, API calls—starts with storing values under names.',
    task: 'Create four variables: table_name as "sales", batch_size as 5000, is_full_load as False, and threshold as 0.95.',
    starter: '# Write the four assignments below\n',
    solution: 'table_name = "sales"\nbatch_size = 5000\nis_full_load = False\nthreshold = 0.95',
    hints: ['Use = for assignment.', 'Strings need quotes. Booleans are True/False with capital first letter.'],
    pitfall: 'Do not write `table_name == "sales"`; `==` compares values, while `=` assigns a value.',
  }),
  L({
    id: 'f-list', track: 'foundations', level: 'Beginner', language: 'python', title: 'Lists: ordered collections',
    concept: 'A list stores multiple values in order. Indexes start at 0 and slicing excludes the end position.',
    why: 'Column names, file paths, IDs, partition values, and task names are often represented as lists.',
    task: 'Create a list named columns with id, customer_id, amount. Then assign the second item to customer_column.',
    starter: '# Create the list and read index 1\n',
    solution: 'columns = ["id", "customer_id", "amount"]\ncustomer_column = columns[1]',
    hints: ['Lists use square brackets [].', 'The second item is index 1.'],
    pitfall: 'Index 2 is the third item, not the second.',
  }),
  L({
    id: 'f-dict', track: 'foundations', level: 'Beginner', language: 'python', title: 'Dictionaries: key → value',
    concept: 'A dictionary maps a key to a value. You look up by key rather than numeric position.',
    why: 'Configuration, JSON objects, metadata, API responses, and lookup tables frequently behave like dictionaries.',
    task: 'Create config with keys source, format, retries. Then read retries into max_retries.',
    starter: '# Build a dictionary\n',
    solution: 'config = {\n    "source": "landing/sales",\n    "format": "parquet",\n    "retries": 3,\n}\nmax_retries = config["retries"]',
    hints: ['Use { key: value }.', 'Dictionary keys are commonly strings.'],
    pitfall: 'A list uses numeric indexes; a dictionary uses keys.',
  }),
  L({
    id: 'f-set', track: 'foundations', level: 'Beginner', language: 'python', title: 'Sets: uniqueness and fast membership',
    concept: 'A set stores unique values and is useful for membership checks such as `x in allowed`.',
    why: 'Deduplication and membership checks appear constantly in validation and data-quality code.',
    task: 'Create a set allowed_status containing NEW, READY, DONE. Write an expression checking whether status is allowed.',
    starter: 'status = "READY"\n# create allowed_status and check membership\n',
    solution: 'status = "READY"\nallowed_status = {"NEW", "READY", "DONE"}\nis_valid = status in allowed_status',
    hints: ['A set can use curly braces like a dict, but contains values rather than key:value pairs.', 'Use `in`.'],
    pitfall: 'An empty set is `set()`, not `{}`—`{}` is an empty dictionary.',
  }),
  L({
    id: 'f-if', track: 'foundations', level: 'Beginner', language: 'python', title: 'if / elif / else',
    concept: 'Conditionals select which block runs. Python uses indentation to define each block.',
    why: 'Pipelines branch on file existence, load type, row counts, status codes, and validation outcomes.',
    task: 'Set mode to "full" when row_count is 0, "large_incremental" when above 1,000,000, otherwise "incremental".',
    starter: 'row_count = 125000\n\n# Write the conditional\n',
    solution: 'row_count = 125000\n\nif row_count == 0:\n    mode = "full"\nelif row_count > 1_000_000:\n    mode = "large_incremental"\nelse:\n    mode = "incremental"',
    hints: ['Conditions end with `:`.', 'Use `elif`, not `else if`.'],
    pitfall: 'Indentation is syntax in Python; the body must be indented.',
  }),
  L({
    id: 'f-for', track: 'foundations', level: 'Beginner', language: 'python', title: 'for loops',
    concept: 'A `for` loop takes one item at a time from an iterable and runs the indented body.',
    why: 'You use loops for small control-plane work: iterate file names, tables, configuration entries, or API pages.',
    task: 'Loop through tables and print `Loading <table>` for each one.',
    starter: 'tables = ["customers", "orders", "products"]\n\n# Write the loop\n',
    solution: 'tables = ["customers", "orders", "products"]\n\nfor table in tables:\n    print(f"Loading {table}")',
    hints: ['Pattern: `for item in collection:`.', 'Use an f-string for the message.'],
    pitfall: 'Do not manually increment an index unless you actually need one.',
  }),
  L({
    id: 'f-while', track: 'foundations', level: 'Intermediate', language: 'python', title: 'while loops and stopping conditions',
    concept: 'A `while` loop repeats while a condition remains true. Something inside must eventually change that condition.',
    why: 'Useful for pagination, polling, and retry-like control flow, but easy to turn into an infinite loop.',
    task: 'Starting with page = 1, print pages 1 to 3 using a while loop.',
    starter: 'page = 1\n\n# Write a while loop\n',
    solution: 'page = 1\n\nwhile page <= 3:\n    print(page)\n    page += 1',
    hints: ['The condition is checked before each iteration.', 'Remember to change `page`.'],
    pitfall: 'If `page` never changes, the loop never ends.',
  }),
  L({
    id: 'f-function', track: 'foundations', level: 'Beginner', language: 'python', title: 'Define a function, arguments, return',
    concept: '`def` creates a reusable function. Parameters are names in the definition; arguments are values supplied when calling it. `return` sends a value back.',
    why: 'This is one of the most important gaps to close: production code is mostly composed from small functions.',
    task: 'Define `qualified_name(schema, table)` that returns `schema.table`. Then call it for dbo and orders.',
    starter: '# Define the function, then call it\n',
    solution: 'def qualified_name(schema, table):\n    return f"{schema}.{table}"\n\nname = qualified_name("dbo", "orders")',
    hints: ['Definition: `def name(parameter1, parameter2):`.', 'Call it later with actual argument values.'],
    pitfall: '`print()` displays a value; `return` gives the value back to the caller. They are not interchangeable.',
  }),
  L({
    id: 'f-default-args', track: 'foundations', level: 'Intermediate', language: 'python', title: 'Default and keyword arguments',
    concept: 'Parameters can have defaults, and calls can name arguments explicitly for clarity.',
    why: 'ETL helpers often have optional behavior such as mode, retries, overwrite, or partition column.',
    task: 'Create `load_table(table, mode="append")` returning `"table:mode"`. Call it once with default mode and once with mode="overwrite".',
    starter: '# Define and call the function twice\n',
    solution: 'def load_table(table, mode="append"):\n    return f"{table}:{mode}"\n\ndefault_run = load_table("orders")\noverwrite_run = load_table("orders", mode="overwrite")',
    hints: ['Defaults are defined with `parameter=value`.', 'Keyword arguments improve readability.'],
    pitfall: 'Required positional parameters must come before defaulted parameters in a normal function signature.',
  }),
  L({
    id: 'f-try', track: 'foundations', level: 'Intermediate', language: 'python', title: 'Exceptions: try / except',
    concept: 'Exceptions represent failures. Catch only errors you can handle meaningfully.',
    why: 'Parsing files, calling APIs, converting types, and reading external systems all fail sometimes.',
    task: 'Convert raw_value to int. If conversion fails with ValueError, set parsed to None.',
    starter: 'raw_value = "not-a-number"\n\n# Handle the conversion safely\n',
    solution: 'raw_value = "not-a-number"\n\ntry:\n    parsed = int(raw_value)\nexcept ValueError:\n    parsed = None',
    hints: ['Put risky code under `try:`.', 'Catch `ValueError` specifically.'],
    pitfall: 'Avoid `except:` unless you truly intend to catch every possible exception.',
  }),
  L({
    id: 'f-big-o', track: 'foundations', level: 'Expert', language: 'python', title: 'Big-O intuition: list vs set membership',
    concept: 'Big-O describes how work grows with input size. List membership is generally O(n); set membership is average O(1).',
    why: 'You do not need algorithm competitions, but you should recognize when repeated linear scans make validation unnecessarily slow.',
    task: 'Rewrite the membership structure so checking many IDs is efficient. Keep the final boolean expression.',
    starter: 'allowed_ids = [101, 102, 103, 104]\ncustomer_id = 103\n\n# Improve the membership structure\nis_allowed = customer_id in allowed_ids\n',
    solution: 'allowed_ids = {101, 102, 103, 104}\ncustomer_id = 103\n\nis_allowed = customer_id in allowed_ids',
    hints: ['Use a set when order and duplicates do not matter.', 'The `in` syntax remains the same.'],
    pitfall: 'Do not blindly convert everything to a set; lists preserve order and allow duplicates.',
  }),

  // ALGORITHMS + DATA STRUCTURES
  L({
    id: 'al-linear-search', track: 'algorithms', level: 'Beginner', language: 'python', title: 'Linear search',
    concept: 'Linear search checks items one by one until it finds a match or reaches the end. Its work grows linearly with the number of items: O(n).',
    why: 'You should recognize the simplest search algorithm before learning when a set/dictionary or sorted search is better.',
    task: 'Loop through table_names. Set found = True when the target table appears, then stop the loop with break.',
    starter: 'table_names = ["customers", "orders", "products"]\ntarget = "orders"\nfound = False\n\n# Search with a loop\n',
    solution: 'table_names = ["customers", "orders", "products"]\ntarget = "orders"\nfound = False\n\nfor table in table_names:\n    if table == target:\n        found = True\n        break',
    hints: ['Check each item with `==`.', 'Use `break` once the target is found.'],
    pitfall: 'For repeated membership checks against a large fixed collection, a set is usually a better lookup structure than rescanning a list every time.',
  }),
  L({
    id: 'al-frequency-map', track: 'algorithms', level: 'Intermediate', language: 'python', title: 'Frequency counting with a dictionary',
    concept: 'A frequency map stores value → count. Each new item increments the count associated with its key.',
    why: 'Counting duplicates/status values is a basic algorithmic pattern behind profiling and data-quality checks.',
    task: 'Build counts so statuses becomes {"OK": 3, "ERROR": 1}.',
    starter: 'statuses = ["OK", "ERROR", "OK", "OK"]\ncounts = {}\n\n# Count each status\n',
    solution: 'statuses = ["OK", "ERROR", "OK", "OK"]\ncounts = {}\n\nfor status in statuses:\n    counts[status] = counts.get(status, 0) + 1',
    hints: ['`dict.get(key, 0)` gives a default count of 0.', 'Increment by 1.'],
    pitfall: 'The algorithmic idea matters more than this exact syntax; `collections.Counter` is a convenient library implementation when allowed.',
  }),
  L({
    id: 'al-dedupe-order', track: 'algorithms', level: 'Intermediate', language: 'python', title: 'Deduplicate while preserving order',
    concept: 'Use a set for fast “have I seen this?” checks and a list for ordered output.',
    why: 'This combines two data structures for different jobs: hash lookup for membership and a list for stable sequence.',
    task: 'Create unique_ids from ids, preserving first-seen order.',
    starter: 'ids = [3, 1, 3, 2, 1]\nseen = set()\nunique_ids = []\n\n# Dedupe in order\n',
    solution: 'ids = [3, 1, 3, 2, 1]\nseen = set()\nunique_ids = []\n\nfor item in ids:\n    if item not in seen:\n        seen.add(item)\n        unique_ids.append(item)',
    hints: ['Check membership in `seen`.', 'Add new items to both structures.'],
    pitfall: '`list(set(ids))` removes duplicates but does not communicate a first-seen-order guarantee as clearly as the explicit pattern.',
  }),
  L({
    id: 'al-stack-queue', track: 'algorithms', level: 'Beginner', language: 'python', title: 'Stack vs queue',
    concept: 'A stack is LIFO: last in, first out. A queue is FIFO: first in, first out.',
    why: 'You mainly need the mental model for interview questions, traversal, buffering, and task-processing discussions.',
    task: 'Use a list as a stack: push "bronze", then "silver", then pop the latest item into current.',
    starter: 'stack = []\n\n# push twice, then pop\n',
    solution: 'stack = []\nstack.append("bronze")\nstack.append("silver")\ncurrent = stack.pop()',
    hints: ['`append` pushes onto the end.', '`pop()` removes and returns the last item.'],
    pitfall: 'For a high-volume FIFO queue in Python, prefer `collections.deque` instead of repeatedly removing index 0 from a list.',
  }),
  L({
    id: 'al-batching', track: 'algorithms', level: 'Intermediate', language: 'python', title: 'Chunk work into batches',
    concept: 'Batching partitions a sequence into fixed-size chunks so work can be processed incrementally.',
    why: 'APIs, database inserts, file operations, and control-plane jobs often need batch limits even when the data engine itself is distributed.',
    task: 'Loop over ids in chunks of batch_size using slicing and print each batch.',
    starter: 'ids = list(range(1, 11))\nbatch_size = 3\n\n# Process chunks\n',
    solution: 'ids = list(range(1, 11))\nbatch_size = 3\n\nfor start in range(0, len(ids), batch_size):\n    batch = ids[start:start + batch_size]\n    print(batch)',
    hints: ['`range(start, stop, step)` can advance by batch_size.', 'Slice from start to start + batch_size.'],
    pitfall: 'Do not manually batch row-level Spark processing on the driver; distributed data engines already partition work and should use their native APIs.',
  }),
  L({
    id: 'al-hash-join', track: 'algorithms', level: 'Expert', language: 'python', title: 'Avoid a nested-loop lookup',
    concept: 'A nested loop can take O(n×m) comparisons. Building a hash lookup first can reduce repeated matching to roughly O(n+m) average work.',
    why: 'This is the intuition behind hash-based joins and why data structures affect algorithm complexity.',
    task: 'Create customer_by_id from customers, then enrich each order with customer_name without an inner loop over customers.',
    starter: 'customers = [\n    {"customer_id": 1, "name": "A"},\n    {"customer_id": 2, "name": "B"},\n]\norders = [\n    {"order_id": 10, "customer_id": 2},\n    {"order_id": 11, "customer_id": 1},\n]\n\n# Build lookup then enrich orders\n',
    solution: 'customer_by_id = {c["customer_id"]: c for c in customers}\n\nfor order in orders:\n    customer = customer_by_id.get(order["customer_id"])\n    order["customer_name"] = customer["name"] if customer else None',
    hints: ['Build a dictionary keyed by customer_id once.', 'Then each order performs one dictionary lookup.'],
    pitfall: 'For real DataFrames, use SQL/pandas/Spark joins rather than writing Python row loops. This exercise teaches the underlying lookup idea.',
  }),
  L({
    id: 'al-binary-search', track: 'algorithms', level: 'Expert', language: 'python', title: 'Binary search intuition',
    concept: 'Binary search repeatedly halves a sorted search space, giving O(log n) search time.',
    why: 'You do not need to hand-code it daily, but it is a classic interview concept and builds intuition for indexes and sorted structures.',
    task: 'Use Python bisect to find the insertion position of target in an already sorted list.',
    starter: 'from bisect import bisect_left\nvalues = [10, 20, 30, 40, 50]\ntarget = 30\n\n# Find insertion/search position\n',
    solution: 'from bisect import bisect_left\nvalues = [10, 20, 30, 40, 50]\ntarget = 30\n\nposition = bisect_left(values, target)\nfound = position < len(values) and values[position] == target',
    hints: ['Binary search requires sorted input.', '`bisect_left` returns where the value should be inserted.'],
    pitfall: 'If you must sort an unsorted list just to perform one search, the sort cost can outweigh the binary-search benefit.',
  }),

  // PYTHON
  L({
    id: 'py-enumerate', track: 'python', level: 'Beginner', language: 'python', title: 'enumerate instead of manual indexes',
    concept: '`enumerate(iterable, start=...)` yields both index and value.',
    why: 'It is the clean way to number files, batches, or tasks.',
    task: 'Print `1 customers.csv`, `2 orders.csv` using enumerate.',
    starter: 'files = ["customers.csv", "orders.csv"]\n\n# Loop with a 1-based counter\n',
    solution: 'files = ["customers.csv", "orders.csv"]\n\nfor number, file_name in enumerate(files, start=1):\n    print(number, file_name)',
    hints: ['Use two loop variables.', 'Pass `start=1`.'],
    pitfall: 'Avoid `range(len(files))` unless you really need index-based access.',
  }),
  L({
    id: 'py-zip', track: 'python', level: 'Intermediate', language: 'python', title: 'zip two collections together',
    concept: '`zip` pairs items at the same position from multiple iterables.',
    why: 'Useful for column mappings and compact control-plane transformations.',
    task: 'Create a dictionary mapping source_cols to target_cols using zip and dict.',
    starter: 'source_cols = ["cust_id", "amt"]\ntarget_cols = ["customer_id", "amount"]\n\n# Build the mapping\n',
    solution: 'source_cols = ["cust_id", "amt"]\ntarget_cols = ["customer_id", "amount"]\n\ncolumn_map = dict(zip(source_cols, target_cols))',
    hints: ['`zip(a, b)` creates pairs.', '`dict(...)` can consume key/value pairs.'],
    pitfall: '`zip` stops at the shortest iterable.',
  }),
  L({
    id: 'py-comprehension', track: 'python', level: 'Intermediate', language: 'python', title: 'List comprehensions',
    concept: 'A comprehension creates a new collection from another iterable, optionally with a filter.',
    why: 'Common for small in-memory metadata transformations; less appropriate for huge datasets that belong in Spark/SQL.',
    task: 'From table names, create a list containing only names starting with `dim_`.',
    starter: 'tables = ["dim_customer", "fact_sales", "dim_product"]\n\n# Create dimensions\n',
    solution: 'tables = ["dim_customer", "fact_sales", "dim_product"]\n\ndimensions = [table for table in tables if table.startswith("dim_")]',
    hints: ['Pattern: `[expression for item in items if condition]`.', 'Use `.startswith()`.'],
    pitfall: 'Prefer readable loops when the comprehension becomes nested or difficult to explain.',
  }),
  L({
    id: 'py-sort-key', track: 'python', level: 'Intermediate', language: 'python', title: 'Sort records with a key function',
    concept: '`sorted(..., key=...)` lets you choose which field controls the ordering.',
    why: 'Useful for small metadata structures, API results, and deterministic configuration output.',
    task: 'Sort jobs by priority ascending using a lambda key.',
    starter: 'jobs = [\n    {"name": "gold", "priority": 3},\n    {"name": "bronze", "priority": 1},\n    {"name": "silver", "priority": 2},\n]\n\n# Sort jobs\n',
    solution: 'jobs = [\n    {"name": "gold", "priority": 3},\n    {"name": "bronze", "priority": 1},\n    {"name": "silver", "priority": 2},\n]\n\nsorted_jobs = sorted(jobs, key=lambda job: job["priority"])',
    hints: ['`key` receives one element.', 'The lambda should return the priority field.'],
    pitfall: '`list.sort()` modifies a list in place; `sorted()` returns a new list.',
  }),
  L({
    id: 'py-json', track: 'python', level: 'Beginner', language: 'python', title: 'Read JSON configuration',
    concept: 'JSON objects map naturally to Python dictionaries.',
    why: 'Pipeline configuration is frequently stored as JSON.',
    task: 'Import json, open config.json using a context manager, and load it into config.',
    starter: '# Read config.json into a dictionary\n',
    solution: 'import json\n\nwith open("config.json", "r", encoding="utf-8") as file:\n    config = json.load(file)',
    hints: ['Use `with open(...) as file:`.', '`json.load(file)` reads from an open file object.'],
    pitfall: '`json.loads()` parses a JSON string; `json.load()` reads from a file-like object.',
  }),
  L({
    id: 'py-pathlib', track: 'python', level: 'Intermediate', language: 'python', title: 'Pathlib for file paths',
    concept: '`pathlib.Path` provides path operations without manually concatenating slashes.',
    why: 'Data engineering scripts often need portable path construction.',
    task: 'Create `/data/landing/orders/2026-09-03` from a base Path and child names using `/` operators.',
    starter: 'from pathlib import Path\n\nbase = Path("/data/landing")\n# Build path\n',
    solution: 'from pathlib import Path\n\nbase = Path("/data/landing")\npath = base / "orders" / "2026-09-03"',
    hints: ['Path objects overload `/` to join path segments.'],
    pitfall: 'Avoid hardcoding Windows backslashes in cross-platform Python when Path can handle it.',
  }),
  L({
    id: 'py-datetime', track: 'python', level: 'Intermediate', language: 'python', title: 'Parse a timestamp',
    concept: '`datetime.strptime` parses a string according to a format string.',
    why: 'Dates arrive as strings from files and APIs, and parsing errors are a common interview topic.',
    task: 'Parse `2026-09-03 14:30:00` into a datetime object.',
    starter: 'from datetime import datetime\nraw = "2026-09-03 14:30:00"\n\n# Parse raw\n',
    solution: 'from datetime import datetime\nraw = "2026-09-03 14:30:00"\n\ntimestamp = datetime.strptime(raw, "%Y-%m-%d %H:%M:%S")',
    hints: ['Year `%Y`, month `%m`, day `%d`, hour `%H`, minute `%M`, second `%S`.'],
    pitfall: 'Be explicit about timezone for production timestamps; naive datetimes can be ambiguous.',
  }),
  L({
    id: 'py-typehint', track: 'python', level: 'Expert', language: 'python', title: 'Type hints for readable helpers',
    concept: 'Type hints document expected inputs and outputs without changing normal Python runtime semantics.',
    why: 'They improve IDE completion and reduce ambiguity in larger pipeline codebases.',
    task: 'Add type hints to a function taking table: str and retries: int and returning str.',
    starter: 'def build_message(table, retries):\n    return f"{table}:{retries}"\n',
    solution: 'def build_message(table: str, retries: int) -> str:\n    return f"{table}:{retries}"',
    hints: ['Parameter annotation: `name: type`.', 'Return annotation: `-> type`.'],
    pitfall: 'Type hints are not automatic runtime validation unless you add separate tooling.',
  }),

  // PANDAS + NUMPY
  L({
    id: 'pd-create', track: 'pandas', level: 'Beginner', language: 'python', title: 'Create a DataFrame',
    concept: 'A pandas DataFrame is a 2D labeled table built from columns and rows.',
    why: 'You should be comfortable constructing a tiny DataFrame for testing transformations.',
    task: 'Create a DataFrame with columns customer_id and amount from the provided lists.',
    starter: 'import pandas as pd\n\ncustomer_ids = [1, 2, 3]\namounts = [10.0, 20.5, 5.0]\n\n# Create df\n',
    solution: 'import pandas as pd\n\ncustomer_ids = [1, 2, 3]\namounts = [10.0, 20.5, 5.0]\n\ndf = pd.DataFrame({\n    "customer_id": customer_ids,\n    "amount": amounts,\n})',
    hints: ['Pass a dictionary of column name to values into `pd.DataFrame`.'],
    pitfall: 'All column arrays must have compatible lengths.',
  }),
  L({
    id: 'pd-filter', track: 'pandas', level: 'Beginner', language: 'python', title: 'Filter DataFrame rows',
    concept: 'Boolean masks select rows where a condition is true.',
    why: 'Filtering is one of the most basic transformations across pandas, SQL, and Spark.',
    task: 'Create high_value containing rows where amount is at least 100.',
    starter: 'import pandas as pd\n\ndf = pd.DataFrame({"amount": [20, 100, 250]})\n\n# Filter rows\n',
    solution: 'import pandas as pd\n\ndf = pd.DataFrame({"amount": [20, 100, 250]})\n\nhigh_value = df[df["amount"] >= 100]',
    hints: ['The inner expression creates True/False values.', 'Use the mask inside `df[...]`.'],
    pitfall: 'Use `&` and `|` for combined pandas conditions, with each condition in parentheses.',
  }),
  L({
    id: 'pd-groupby', track: 'pandas', level: 'Intermediate', language: 'python', title: 'Group and aggregate',
    concept: '`groupby` splits rows by key, aggregation summarizes each group.',
    why: 'This is the pandas equivalent of SQL GROUP BY and a core DE transformation pattern.',
    task: 'Calculate total amount per customer_id and return a DataFrame with `total_amount`.',
    starter: 'import pandas as pd\n\ndf = pd.DataFrame({\n    "customer_id": [1, 1, 2],\n    "amount": [10, 15, 20],\n})\n\n# Group and sum\n',
    solution: 'import pandas as pd\n\ndf = pd.DataFrame({\n    "customer_id": [1, 1, 2],\n    "amount": [10, 15, 20],\n})\n\nresult = (\n    df.groupby("customer_id", as_index=False)\n      .agg(total_amount=("amount", "sum"))\n)',
    hints: ['Group by customer_id.', 'Named aggregation syntax can create `total_amount`.'],
    pitfall: 'Know whether your group key becomes an index; `as_index=False` often keeps output easier to use.',
  }),
  L({
    id: 'pd-merge', track: 'pandas', level: 'Intermediate', language: 'python', title: 'Merge like a SQL join',
    concept: '`merge` combines DataFrames using key columns and a join type.',
    why: 'You need to translate the same join mental model between SQL, pandas, and Spark.',
    task: 'Left join orders to customers on customer_id.',
    starter: 'import pandas as pd\n\n# Assume orders and customers already exist\n# Write the merge\n',
    solution: 'result = orders.merge(\n    customers,\n    how="left",\n    on="customer_id",\n)',
    hints: ['Use `how="left"`.', 'Use `on="customer_id"`.'],
    pitfall: 'pandas can match null keys with each other in merge behavior, which differs from usual SQL null join semantics.',
  }),
  L({
    id: 'pd-dedupe', track: 'pandas', level: 'Intermediate', language: 'python', title: 'Keep the latest record per key',
    concept: 'Sort so the desired row comes last, then drop duplicates by business key.',
    why: 'Latest-record deduplication is a classic ingestion pattern.',
    task: 'Keep only the latest row per customer_id using updated_at.',
    starter: '# df has customer_id and updated_at\n# Write the two-step dedupe\n',
    solution: 'latest = (\n    df.sort_values("updated_at")\n      .drop_duplicates(subset=["customer_id"], keep="last")\n)',
    hints: ['Sort by the timestamp first.', 'Then drop duplicate customer_id values keeping the last.'],
    pitfall: 'Without sorting first, “last” only means last in the current row order.',
  }),
  L({
    id: 'np-vector', track: 'pandas', level: 'Expert', language: 'python', title: 'NumPy vectorization vs Python loop',
    concept: 'NumPy operates over arrays in compiled/vectorized operations instead of Python-level element loops.',
    why: 'For local numerical work, vectorized expressions are generally clearer and faster than manual element-by-element loops.',
    task: 'Create net_amount by multiplying the NumPy array amounts by 0.8 without writing a loop.',
    starter: 'import numpy as np\namounts = np.array([10.0, 20.0, 30.0])\n\n# Vectorized calculation\n',
    solution: 'import numpy as np\namounts = np.array([10.0, 20.0, 30.0])\n\nnet_amount = amounts * 0.8',
    hints: ['Arithmetic operators work element-wise on NumPy arrays.'],
    pitfall: 'Do not apply pandas/NumPy local processing to datasets that exceed the machine’s practical memory limits; that is where distributed engines may be appropriate.',
  }),

  // SQL
  L({
    id: 'sql-basic', track: 'sql', level: 'Beginner', language: 'sql', title: 'SELECT / WHERE / ORDER BY',
    concept: 'SELECT chooses columns, WHERE filters rows, ORDER BY sorts the final result.',
    why: 'This is the minimum syntax you should be able to write instantly.',
    task: 'Return customer_id and amount from dbo.sales where amount > 100, newest order_date first.',
    starter: '-- Write the query\n',
    solution: 'SELECT\n    customer_id,\n    amount\nFROM dbo.sales\nWHERE amount > 100\nORDER BY order_date DESC;',
    hints: ['Filtering comes before ordering logically in the query text.', 'Descending sort uses DESC.'],
    pitfall: 'Do not assume row order without ORDER BY.',
  }),
  L({
    id: 'sql-join', track: 'sql', level: 'Beginner', language: 'sql', title: 'LEFT JOIN',
    concept: 'A LEFT JOIN keeps all rows from the left table and matches rows from the right when the join condition succeeds.',
    why: 'Joins are fundamental to dimensional models and warehouse transformations.',
    task: 'Return every order with customer_name when available.',
    starter: 'SELECT\n    o.order_id,\n    o.customer_id\n    -- add customer name\nFROM dbo.orders AS o\n-- add the join\n',
    solution: 'SELECT\n    o.order_id,\n    o.customer_id,\n    c.customer_name\nFROM dbo.orders AS o\nLEFT JOIN dbo.customers AS c\n    ON o.customer_id = c.customer_id;',
    hints: ['Orders is the left table.', 'Join on customer_id.'],
    pitfall: 'A join without the correct ON condition can multiply rows unexpectedly.',
  }),
  L({
    id: 'sql-group', track: 'sql', level: 'Intermediate', language: 'sql', title: 'GROUP BY and HAVING',
    concept: 'GROUP BY forms groups; aggregate functions summarize each group; HAVING filters after aggregation.',
    why: 'The WHERE vs HAVING distinction is a frequent interview question.',
    task: 'Return customers whose total amount is greater than 1000.',
    starter: '-- Aggregate dbo.sales by customer_id\n',
    solution: 'SELECT\n    customer_id,\n    SUM(amount) AS total_amount\nFROM dbo.sales\nGROUP BY customer_id\nHAVING SUM(amount) > 1000;',
    hints: ['Use WHERE for row-level filters before grouping.', 'Use HAVING for aggregate conditions.'],
    pitfall: 'You cannot normally filter `SUM(amount)` with WHERE because WHERE is evaluated before aggregation.',
  }),
  L({
    id: 'sql-case', track: 'sql', level: 'Intermediate', language: 'sql', title: 'CASE expression',
    concept: 'CASE is SQL branching: it returns a value based on ordered conditions.',
    why: 'Used for bucketing, flags, normalization, and conditional transformations.',
    task: 'Create size_band: high if amount >= 1000, medium if >= 100, otherwise low.',
    starter: 'SELECT\n    amount,\n    -- add CASE\nFROM dbo.sales;\n',
    solution: 'SELECT\n    amount,\n    CASE\n        WHEN amount >= 1000 THEN \'high\'\n        WHEN amount >= 100 THEN \'medium\'\n        ELSE \'low\'\n    END AS size_band\nFROM dbo.sales;',
    hints: ['CASE ends with END.', 'Order conditions from most specific/highest threshold downward.'],
    pitfall: 'The first matching WHEN wins.',
  }),
  L({
    id: 'sql-cte', track: 'sql', level: 'Intermediate', language: 'sql', title: 'CTE for readable transformations',
    concept: 'A common table expression names an intermediate query for use by the next statement.',
    why: 'CTEs make multi-step transformation logic easier to read and interview on.',
    task: 'Create a CTE called filtered_sales for amount > 100, then count its rows.',
    starter: '-- Write a CTE then select from it\n',
    solution: 'WITH filtered_sales AS (\n    SELECT *\n    FROM dbo.sales\n    WHERE amount > 100\n)\nSELECT COUNT(*) AS row_count\nFROM filtered_sales;',
    hints: ['Pattern: `WITH name AS (...) SELECT ... FROM name`.', 'A CTE is scoped to the following statement.'],
    pitfall: 'A CTE is not automatically materialized storage; the optimizer decides execution.',
  }),
  L({
    id: 'sql-row-number', track: 'sql', level: 'Intermediate', language: 'sql', title: 'ROW_NUMBER for latest row per key',
    concept: 'Window functions compute values across related rows without collapsing them like GROUP BY.',
    why: 'Latest-row deduplication is one of the most common DE interview SQL patterns.',
    task: 'Rank each customer’s rows newest first by updated_at.',
    starter: 'SELECT\n    customer_id,\n    updated_at,\n    -- add row number\nFROM dbo.customer_updates;\n',
    solution: 'SELECT\n    customer_id,\n    updated_at,\n    ROW_NUMBER() OVER (\n        PARTITION BY customer_id\n        ORDER BY updated_at DESC\n    ) AS rn\nFROM dbo.customer_updates;',
    hints: ['PARTITION BY restarts numbering for each customer.', 'Newest first requires DESC.'],
    pitfall: 'If timestamps can tie, add a deterministic tie-breaker to ORDER BY.',
  }),
  L({
    id: 'sql-dedupe', track: 'sql', level: 'Expert', language: 'sql', title: 'Deduplicate with ROW_NUMBER + CTE',
    concept: 'Rank rows inside each business key, then keep rn = 1.',
    why: 'This combines windowing and CTE syntax into an interview-ready dedupe solution.',
    task: 'Return only the latest record per customer_id from dbo.customer_updates.',
    starter: '-- Use a CTE and ROW_NUMBER\n',
    solution: 'WITH ranked AS (\n    SELECT\n        *,\n        ROW_NUMBER() OVER (\n            PARTITION BY customer_id\n            ORDER BY updated_at DESC\n        ) AS rn\n    FROM dbo.customer_updates\n)\nSELECT *\nFROM ranked\nWHERE rn = 1;',
    hints: ['Build the rank first.', 'Filter rn after the window function is computed.'],
    pitfall: 'T-SQL does not have a general QUALIFY clause, so the CTE/subquery pattern is standard.',
  }),
  L({
    id: 'sql-pk-fk', track: 'sql', level: 'Beginner', language: 'sql', title: 'Primary key vs foreign key',
    concept: 'A primary key uniquely identifies a row in its table. A foreign key references a key in another table to enforce a relationship.',
    why: 'This is basic relational modeling and frequently asked even for experienced DE roles.',
    task: 'Write CREATE TABLE statements for customers with customer_id PK and orders with order_id PK plus customer_id FK.',
    starter: '-- Create the two simplified tables\n',
    solution: 'CREATE TABLE dbo.customers (\n    customer_id INT NOT NULL PRIMARY KEY,\n    customer_name NVARCHAR(200) NOT NULL\n);\n\nCREATE TABLE dbo.orders (\n    order_id INT NOT NULL PRIMARY KEY,\n    customer_id INT NOT NULL,\n    amount DECIMAL(18, 2) NOT NULL,\n    CONSTRAINT FK_orders_customers\n        FOREIGN KEY (customer_id) REFERENCES dbo.customers(customer_id)\n);',
    hints: ['Each table can have its own primary key.', 'The child table holds the foreign key.'],
    pitfall: 'A primary key is about row identity; a foreign key is about referential integrity.',
  }),
  L({
    id: 'sql-scd2', track: 'sql', level: 'Expert', language: 'sql', title: 'SCD Type 2 mental model',
    concept: 'SCD Type 2 preserves history by expiring the old dimension row and inserting a new version when tracked attributes change.',
    why: 'This is a classic data engineering interview topic and a key dimensional-modeling concept.',
    task: 'Write the UPDATE that expires the current customer row when its city changed. Assume #stage contains customer_id and city, and dim_customer has is_current and valid_to.',
    starter: '-- Expire only changed current rows\n',
    solution: 'UPDATE d\nSET\n    d.is_current = 0,\n    d.valid_to = SYSUTCDATETIME()\nFROM dbo.dim_customer AS d\nINNER JOIN #stage AS s\n    ON d.customer_id = s.customer_id\nWHERE d.is_current = 1\n  AND ISNULL(d.city, \'\') <> ISNULL(s.city, \'\');\n\n-- Next step: INSERT a new current version for new/changed business keys.',
    hints: ['Match on the business key.', 'Only expire the current version.', 'Compare tracked attributes.'],
    pitfall: 'SCD2 normally needs both steps: expire old version and insert new version. Use a surrogate dimension key if downstream facts must reference a specific historical version.',
  }),

  // PYSPARK
  L({
    id: 'sp-session', track: 'pyspark', level: 'Beginner', language: 'python', title: 'SparkSession and read Parquet',
    concept: 'The SparkSession is the main entry point for DataFrame APIs in PySpark.',
    why: 'In managed notebooks `spark` may already exist, but you should still recognize what it represents.',
    task: 'Create/get a SparkSession named de-lab and read `/lake/bronze/orders` as Parquet.',
    starter: 'from pyspark.sql import SparkSession\n\n# Create/get SparkSession and read parquet\n',
    solution: 'from pyspark.sql import SparkSession\n\nspark = SparkSession.builder.appName("de-lab").getOrCreate()\norders = spark.read.parquet("/lake/bronze/orders")',
    hints: ['Use `.builder.appName(...).getOrCreate()`.', 'Parquet has a convenience reader.'],
    pitfall: 'On Databricks/Fabric notebooks a preconfigured `spark` session is usually provided; creating a second session is generally unnecessary there.',
  }),
  L({
    id: 'sp-filter-select', track: 'pyspark', level: 'Beginner', language: 'python', title: 'select and filter',
    concept: 'Spark transformations create a new DataFrame; they do not mutate the existing one in place.',
    why: 'Selecting and filtering are foundational lazy transformations.',
    task: 'From orders, keep customer_id and amount for rows where amount > 100.',
    starter: 'from pyspark.sql import functions as F\n\n# Transform orders\n',
    solution: 'from pyspark.sql import functions as F\n\nresult = (\n    orders\n    .filter(F.col("amount") > 100)\n    .select("customer_id", "amount")\n)',
    hints: ['Use `F.col("amount")` for a column expression.', 'Chain transformations.'],
    pitfall: 'Avoid collecting large Spark DataFrames to the driver just to filter them in Python.',
  }),
  L({
    id: 'sp-withcolumn', track: 'pyspark', level: 'Intermediate', language: 'python', title: 'withColumn and when',
    concept: '`withColumn` adds/replaces a column from a Spark expression; `when` implements conditional logic.',
    why: 'This is the Spark equivalent of SQL CASE for many transformations.',
    task: 'Add `size_band`: high if amount >= 1000, otherwise normal.',
    starter: 'from pyspark.sql import functions as F\n\n# Add size_band\n',
    solution: 'from pyspark.sql import functions as F\n\nresult = orders.withColumn(\n    "size_band",\n    F.when(F.col("amount") >= 1000, F.lit("high"))\n     .otherwise(F.lit("normal")),\n)',
    hints: ['Use `F.when(condition, value).otherwise(value)`.', 'Wrap string literals with `F.lit`.'],
    pitfall: 'Spark column expressions are not normal Python booleans; use Spark functions/operators to build expressions.',
  }),
  L({
    id: 'sp-groupby', track: 'pyspark', level: 'Intermediate', language: 'python', title: 'groupBy and aggregate',
    concept: 'groupBy creates grouped data; agg computes summaries such as sum, count, max.',
    why: 'Same logical pattern as SQL GROUP BY, but expressed through the DataFrame API.',
    task: 'Calculate total_amount by customer_id.',
    starter: 'from pyspark.sql import functions as F\n\n# Group and aggregate\n',
    solution: 'from pyspark.sql import functions as F\n\nresult = (\n    orders\n    .groupBy("customer_id")\n    .agg(F.sum("amount").alias("total_amount"))\n)',
    hints: ['Use `F.sum`.', 'Rename the aggregate with `.alias()`.'],
    pitfall: 'Aggregations and joins can cause shuffles; distributed performance depends heavily on data size and partitioning.',
  }),
  L({
    id: 'sp-join', track: 'pyspark', level: 'Intermediate', language: 'python', title: 'Join DataFrames',
    concept: 'Spark joins combine distributed DataFrames on one or more keys.',
    why: 'You should be able to translate a SQL left join directly into PySpark syntax.',
    task: 'Left join orders with customers on customer_id.',
    starter: '# Assume orders and customers are DataFrames\n# Write the join\n',
    solution: 'result = orders.join(\n    customers,\n    on="customer_id",\n    how="left",\n)',
    hints: ['Use `on=` and `how=` named arguments.'],
    pitfall: 'Duplicate column names after joins can become ambiguous; select or alias deliberately.',
  }),
  L({
    id: 'sp-window', track: 'pyspark', level: 'Expert', language: 'python', title: 'Window deduplication',
    concept: 'A Spark Window defines partitioning and ordering for window functions such as row_number.',
    why: 'Latest-record dedupe is a canonical PySpark interview pattern.',
    task: 'Keep the newest customer update per customer_id using updated_at.',
    starter: 'from pyspark.sql import functions as F\nfrom pyspark.sql.window import Window\n\n# Define window, rank, filter\n',
    solution: 'from pyspark.sql import functions as F\nfrom pyspark.sql.window import Window\n\nw = Window.partitionBy("customer_id").orderBy(F.col("updated_at").desc())\n\nlatest = (\n    updates\n    .withColumn("rn", F.row_number().over(w))\n    .filter(F.col("rn") == 1)\n    .drop("rn")\n)',
    hints: ['Partition by the business key.', 'Order newest first.', 'Filter row_number 1.'],
    pitfall: 'Add a tie-breaker if updated_at is not unique within a business key.',
  }),
  L({
    id: 'sp-write', track: 'pyspark', level: 'Intermediate', language: 'python', title: 'Write Parquet partitioned by date',
    concept: 'DataFrameWriter controls output format, mode, partitioning, and destination.',
    why: 'Writing data is where partition choices and overwrite semantics become operationally important.',
    task: 'Overwrite `/lake/silver/orders` as Parquet partitioned by order_date.',
    starter: '# Write result DataFrame\n',
    solution: '(\n    result.write\n    .mode("overwrite")\n    .partitionBy("order_date")\n    .parquet("/lake/silver/orders")\n)',
    hints: ['Start from `result.write`.', 'Set mode before the final format/path call.'],
    pitfall: 'Do not partition on a very high-cardinality column by habit; too many tiny partitions/files can hurt performance.',
  }),

  // DAX
  L({
    id: 'dax-measure', track: 'dax', level: 'Beginner', language: 'dax', title: 'Basic measure',
    concept: 'A measure is evaluated in filter context and returns a scalar value.',
    why: 'Measures are the basic unit of reusable business logic in Power BI semantic models.',
    task: 'Create a Total Sales measure summing Sales[Amount].',
    starter: 'Total Sales =\n',
    solution: 'Total Sales =\nSUM(Sales[Amount])',
    hints: ['Use SUM for a simple column total.'],
    pitfall: 'A measure is not stored row-by-row like a calculated column.',
  }),
  L({
    id: 'dax-var', track: 'dax', level: 'Beginner', language: 'dax', title: 'VAR / RETURN',
    concept: 'Variables store intermediate scalar or table expressions and improve readability.',
    why: 'Complex DAX is far easier to debug when broken into named steps.',
    task: 'Create Margin % using variables SalesAmount and CostAmount, then DIVIDE the difference by sales.',
    starter: 'Margin % =\nVAR SalesAmount = [Total Sales]\n-- add CostAmount and return expression\n',
    solution: 'Margin % =\nVAR SalesAmount = [Total Sales]\nVAR CostAmount = [Total Cost]\nRETURN\n    DIVIDE(SalesAmount - CostAmount, SalesAmount)',
    hints: ['Define variables first.', 'Use DIVIDE instead of `/` when denominator safety matters.'],
    pitfall: 'Variables are immutable within one measure evaluation.',
  }),
  L({
    id: 'dax-calculate', track: 'dax', level: 'Intermediate', language: 'dax', title: 'CALCULATE changes filter context',
    concept: 'CALCULATE evaluates an expression under modified filter context.',
    why: 'Understanding CALCULATE is central to understanding DAX.',
    task: 'Create France Sales from [Total Sales] filtered to Customer[Country] = "France".',
    starter: 'France Sales =\n',
    solution: 'France Sales =\nCALCULATE(\n    [Total Sales],\n    Customer[Country] = "France"\n)',
    hints: ['First argument is the expression.', 'Later arguments modify filters.'],
    pitfall: 'The difficult part of DAX is usually context, not syntax. Ask: what filters exist before and after CALCULATE?',
  }),
  L({
    id: 'dax-sumx', track: 'dax', level: 'Intermediate', language: 'dax', title: 'SUMX iterator',
    concept: 'SUMX iterates rows of a table, evaluates an expression per row, and sums the results.',
    why: 'You need iterators when the value to aggregate is an expression, not simply one stored numeric column.',
    task: 'Calculate Gross Sales as Quantity * UnitPrice for each row of Sales.',
    starter: 'Gross Sales =\n',
    solution: 'Gross Sales =\nSUMX(\n    Sales,\n    Sales[Quantity] * Sales[UnitPrice]\n)',
    hints: ['First argument is the table to iterate.', 'Second is the row expression.'],
    pitfall: 'Prefer SUM when a simple stored column sum is all you need; iterators do extra row-by-row expression work.',
  }),
  L({
    id: 'dax-filter', track: 'dax', level: 'Expert', language: 'dax', title: 'FILTER returns a table',
    concept: 'FILTER returns a subset table and is often nested inside functions that accept a table.',
    why: 'It is important to distinguish table-returning functions from scalar-returning functions in DAX.',
    task: 'Create High Value Sales by calculating [Total Sales] only over Sales rows where Amount > 1000.',
    starter: 'High Value Sales =\n',
    solution: 'High Value Sales =\nCALCULATE(\n    [Total Sales],\n    FILTER(\n        Sales,\n        Sales[Amount] > 1000\n    )\n)',
    hints: ['FILTER needs a table and a Boolean condition.', 'Use the resulting table inside CALCULATE.'],
    pitfall: 'Do not reach for FILTER automatically when a simple Boolean filter argument to CALCULATE is sufficient.',
  }),

  // C# TABULAR EDITOR
  L({
    id: 'cs-var', track: 'csharp', level: 'Beginner', language: 'csharp', title: 'C# variables and semicolons',
    concept: 'C# statements commonly end with semicolons. `var` asks the compiler to infer the static type from the assigned expression.',
    why: 'Tabular Editor scripts are C#, so basic statement syntax must feel familiar.',
    task: 'Create tableName as "Sales" and folder as "Measures" using var.',
    starter: '// Write two variable declarations\n',
    solution: 'var tableName = "Sales";\nvar folder = "Measures";',
    hints: ['Strings use double quotes.', 'End each statement with `;`.'],
    pitfall: 'C# `var` is still statically typed; it does not mean the variable can freely change to unrelated types later.',
  }),
  L({
    id: 'cs-foreach', track: 'csharp', level: 'Beginner', language: 'csharp', title: 'foreach loop',
    concept: '`foreach` iterates each item in a collection.',
    why: 'Bulk-editing selected measures is one of the most useful Tabular Editor scripting patterns.',
    task: 'Loop through Selected.Measures and set DisplayFolder to "KPIs".',
    starter: '// Loop selected measures\n',
    solution: 'foreach (var measure in Selected.Measures)\n{\n    measure.DisplayFolder = "KPIs";\n}',
    hints: ['C# uses braces `{}` for the loop body.', 'Each property assignment ends with `;`.'],
    pitfall: 'Be sure the selection contains the object type your script expects.',
  }),
  L({
    id: 'cs-if', track: 'csharp', level: 'Intermediate', language: 'csharp', title: 'Conditional bulk edit',
    concept: 'C# uses parentheses around an `if` condition and braces around the body.',
    why: 'You often want to modify only objects matching a naming or folder rule.',
    task: 'For selected measures, set DisplayFolder to "Ratios" only when the name ends with `%`.',
    starter: 'foreach (var measure in Selected.Measures)\n{\n    // add condition\n}\n',
    solution: 'foreach (var measure in Selected.Measures)\n{\n    if (measure.Name.EndsWith("%"))\n    {\n        measure.DisplayFolder = "Ratios";\n    }\n}',
    hints: ['Strings expose `.EndsWith(...)`.', 'Nest the if inside foreach.'],
    pitfall: 'C# method names are case-sensitive.',
  }),
  L({
    id: 'cs-linq', track: 'csharp', level: 'Expert', language: 'csharp', title: 'LINQ Where',
    concept: 'LINQ provides query-style operations over collections; `Where` filters items using a lambda.',
    why: 'Tabular Editor scripting becomes concise once you can read simple LINQ expressions.',
    task: 'Create a variable named hiddenTables containing model tables where IsHidden is true.',
    starter: '// Filter Model.Tables with LINQ\n',
    solution: 'var hiddenTables = Model.Tables.Where(t => t.IsHidden);',
    hints: ['Lambda syntax: `t => condition`.', 'Use `.Where(...)`.'],
    pitfall: 'LINQ can become unreadable when heavily chained. Prefer explicit loops when they communicate intent better.',
  }),
  L({
    id: 'cs-add-measure', track: 'csharp', level: 'Expert', language: 'csharp', title: 'Create a measure with Tabular Editor',
    concept: 'Tabular Editor exposes `Model` and `Selected` objects for scripting against the loaded semantic model.',
    why: 'Creating or mass-updating measures is where C# scripting becomes directly valuable to a Power BI developer.',
    task: 'Add measure `Row Count` to the Sales table with expression `COUNTROWS(Sales)` and display folder `Technical`.',
    starter: '// Get Sales table and add a measure\n',
    solution: 'var table = Model.Tables["Sales"];\nvar measure = table.AddMeasure("Row Count", "COUNTROWS(Sales)");\nmeasure.DisplayFolder = "Technical";',
    hints: ['Get the table from `Model.Tables[...]`.', 'Use `AddMeasure(name, expression)`.'],
    pitfall: 'Test bulk scripts on a copy/model branch first. External-tool capabilities can differ depending on Tabular Editor version and the connected model.',
  }),

  // AIRFLOW
  L({
    id: 'af-basic', track: 'airflow', level: 'Beginner', language: 'python', title: 'Minimal Airflow 3 DAG',
    concept: 'A DAG defines orchestration structure; tasks represent units of work. Airflow 3 provides a stable authoring API under `airflow.sdk`.',
    why: 'You should be able to recognize the smallest modern DAG even if you are not an Airflow specialist.',
    task: 'Complete a DAG with one `extract` task that prints "extract".',
    starter: 'from airflow.sdk import dag, task\n\n@dag(schedule=None, catchup=False)\ndef de_pipeline():\n    # define task here\n    pass\n\nde_pipeline()\n',
    solution: 'from airflow.sdk import dag, task\n\n@dag(schedule=None, catchup=False)\ndef de_pipeline():\n    @task\n    def extract():\n        print("extract")\n\n    extract()\n\nde_pipeline()',
    hints: ['Nest an `@task` function inside the DAG function.', 'Call the task function to place a task in the DAG.'],
    pitfall: 'Defining Python functions is not enough; task calls establish task instances/relationships in the DAG.',
  }),
  L({
    id: 'af-dependencies', track: 'airflow', level: 'Intermediate', language: 'python', title: 'Task dependencies with >>',
    concept: '`a >> b` means task b depends on task a.',
    why: 'Readable dependency graphs are the heart of orchestration code.',
    task: 'Given task objects extract, transform, load, make them run in ETL order.',
    starter: '# Task objects already exist\n# Define dependency order\n',
    solution: 'extract >> transform >> load',
    hints: ['Read `>>` as “then”.'],
    pitfall: 'Dependencies define order, not data transport. Keep data passing explicit and small.',
  }),
  L({
    id: 'af-schedule', track: 'airflow', level: 'Intermediate', language: 'python', title: 'Schedule and catchup',
    concept: 'The DAG schedule defines when logical runs are created; catchup controls whether historical intervals are automatically created.',
    why: 'Scheduling semantics are a frequent source of unexpected backfills.',
    task: 'Write a @dag decorator for a daily schedule with catchup disabled.',
    starter: 'from airflow.sdk import dag\n\n# add decorator\ndef daily_load():\n    pass\n',
    solution: 'from airflow.sdk import dag\n\n@dag(schedule="@daily", catchup=False)\ndef daily_load():\n    pass',
    hints: ['Use `schedule="@daily"`.', 'Set `catchup=False`.'],
    pitfall: 'A daily schedule is about logical data intervals, not simply “sleep 24 hours after the previous run”.',
  }),
  L({
    id: 'af-idempotent', track: 'airflow', level: 'Expert', language: 'python', title: 'Idempotent task design',
    concept: 'An idempotent task can be retried without creating an incorrect duplicate side effect.',
    why: 'Retries are normal in orchestration. Data jobs should use deterministic partitions/keys, merges, or overwrite semantics rather than blind append when retries are possible.',
    task: 'Choose the safer write pattern by replacing the blind append comment with a deterministic overwrite for one partition (pseudocode is fine).',
    starter: 'def load_partition(run_date):\n    # BAD: append_same_partition_again()\n    # Write a retry-safe intent below\n    pass\n',
    solution: 'def load_partition(run_date):\n    partition_path = f"/gold/sales/run_date={run_date}"\n    overwrite_partition(partition_path)',
    hints: ['Make the target deterministic from run_date.', 'Retry should replace/reconcile the same target, not create a second copy.'],
    pitfall: 'Idempotency is a system-design property; syntax alone cannot guarantee it.',
  }),

  // BASH SSH
  L({
    id: 'sh-nav', track: 'bash', level: 'Beginner', language: 'shell', title: 'Navigate a Linux terminal',
    concept: '`pwd` shows the current directory, `ls` lists entries, `cd` changes directory.',
    why: 'You cannot troubleshoot a Linux VM or container if directory navigation is not automatic.',
    task: 'Write commands to show the current directory, list files including hidden entries, then move to /opt/etl.',
    starter: '# One command per line\n',
    solution: 'pwd\nls -la\ncd /opt/etl',
    hints: ['`-a` includes hidden files; `-l` shows a long listing.'],
    pitfall: 'Linux paths and names are case-sensitive.',
  }),
  L({
    id: 'sh-pipe', track: 'bash', level: 'Intermediate', language: 'shell', title: 'Pipe and grep logs',
    concept: 'A pipe `|` sends stdout from one command into the next command’s stdin.',
    why: 'Combining small commands is a core Unix troubleshooting skill.',
    task: 'Show the last 200 lines of pipeline.log and keep only lines containing ERROR.',
    starter: '# Use tail and grep with a pipe\n',
    solution: 'tail -n 200 pipeline.log | grep "ERROR"',
    hints: ['First produce the last 200 lines.', 'Pipe them into grep.'],
    pitfall: 'A pipe connects command streams; it does not modify the original file.',
  }),
  L({
    id: 'sh-env', track: 'bash', level: 'Intermediate', language: 'shell', title: 'Environment variables',
    concept: 'Environment variables pass configuration to processes without hardcoding values in source code.',
    why: 'Connection endpoints, environment names, and non-secret configuration are commonly injected this way.',
    task: 'Set ENVIRONMENT to prod for the current shell, then print it.',
    starter: '# Set and print ENVIRONMENT\n',
    solution: 'export ENVIRONMENT="prod"\necho "$ENVIRONMENT"',
    hints: ['Use `export NAME=value`.', 'Read a variable with `$NAME`.'],
    pitfall: 'Do not paste long-lived secrets into shell history. Use your platform’s secret/identity mechanism.',
  }),
  L({
    id: 'sh-ssh', track: 'bash', level: 'Beginner', language: 'shell', title: 'SSH into a remote Linux VM',
    concept: 'SSH provides encrypted remote shell access using a host, username, and usually key-based authentication.',
    why: 'External VM access is a basic operational skill for data engineers.',
    task: 'Connect as user `deuser` to host `10.20.30.40` with SSH.',
    starter: '# SSH command\n',
    solution: 'ssh deuser@10.20.30.40',
    hints: ['Pattern: `ssh user@host`.'],
    pitfall: 'Prefer key-based or organization-managed authentication; never put a password directly in the command.',
  }),
  L({
    id: 'sh-scp', track: 'bash', level: 'Intermediate', language: 'shell', title: 'Copy a file to a VM with scp',
    concept: '`scp` copies files over SSH.',
    why: 'Useful for small scripts/configs during controlled troubleshooting, though production deployment should normally use CI/CD or managed tooling.',
    task: 'Copy job.py to `/opt/etl/job.py` on deuser@10.20.30.40.',
    starter: '# scp command\n',
    solution: 'scp job.py deuser@10.20.30.40:/opt/etl/job.py',
    hints: ['Local source first, remote destination second.', 'Remote syntax is `user@host:/path`.'],
    pitfall: 'For repeatable production changes, prefer version-controlled deployment instead of manual copying.',
  }),

  // POWERSHELL
  L({
    id: 'ps-list', track: 'powershell', level: 'Beginner', language: 'powershell', title: 'List files with Get-ChildItem',
    concept: 'PowerShell commands operate on structured objects, not only text streams.',
    why: 'Get-ChildItem is the PowerShell equivalent you will use constantly for filesystem inspection.',
    task: 'List files under C:\\ETL recursively.',
    starter: '# PowerShell command\n',
    solution: 'Get-ChildItem -Path C:\\ETL -Recurse',
    hints: ['Use `-Path` and `-Recurse`.'],
    pitfall: 'PowerShell aliases like `ls` are convenient interactively, but full cmdlet names are clearer in scripts.',
  }),
  L({
    id: 'ps-filter', track: 'powershell', level: 'Intermediate', language: 'powershell', title: 'Filter objects in a pipeline',
    concept: 'PowerShell pipes pass objects; `Where-Object` filters them by properties.',
    why: 'This is fundamentally different from Bash text piping and worth practicing explicitly.',
    task: 'List services whose Status is Running.',
    starter: '# Get services then filter them\n',
    solution: 'Get-Service | Where-Object { $_.Status -eq "Running" }',
    hints: ['`$_` means the current pipeline object.', 'String equality operator is `-eq`.'],
    pitfall: 'Do not assume Bash operators and PowerShell operators are identical.',
  }),
  L({
    id: 'ps-port', track: 'powershell', level: 'Intermediate', language: 'powershell', title: 'Test network connectivity',
    concept: '`Test-NetConnection` can check whether a host/port is reachable from a Windows VM.',
    why: 'Gateway and database connectivity issues often begin with basic DNS/network/port checks.',
    task: 'Test TCP connectivity to sql.internal.local on port 1433.',
    starter: '# Test host and port\n',
    solution: 'Test-NetConnection -ComputerName sql.internal.local -Port 1433',
    hints: ['SQL Server commonly listens on TCP 1433 when configured for the default port.'],
    pitfall: 'A successful TCP test does not prove database credentials, TLS settings, or permissions are correct.',
  }),
  L({
    id: 'ps-rest', track: 'powershell', level: 'Expert', language: 'powershell', title: 'Call a JSON API',
    concept: '`Invoke-RestMethod` calls HTTP endpoints and parses common structured response formats such as JSON into PowerShell objects.',
    why: 'Useful for automation and quick API inspection on Windows.',
    task: 'GET https://example.com/api/status and store the response in $response.',
    starter: '# Call the endpoint\n',
    solution: '$response = Invoke-RestMethod -Method Get -Uri "https://example.com/api/status"',
    hints: ['Use `-Method Get` and `-Uri`.'],
    pitfall: 'Do not hardcode bearer tokens into scripts or shell history.',
  }),

  // GIT
  L({
    id: 'git-status', track: 'git', level: 'Beginner', language: 'shell', title: 'Inspect before changing anything',
    concept: '`git status` shows branch and working-tree/index state; `git diff` shows unstaged changes.',
    why: 'The safest Git habit is to inspect state before stage/commit/pull operations.',
    task: 'Write commands to see repo status and then inspect unstaged changes.',
    starter: '# Two commands\n',
    solution: 'git status\ngit diff',
    hints: ['Status first, diff second.'],
    pitfall: 'Do not run destructive recovery commands when you have not first inspected what is modified or untracked.',
  }),
  L({
    id: 'git-commit', track: 'git', level: 'Beginner', language: 'shell', title: 'Stage and commit one file',
    concept: '`git add` stages content into the index; `git commit` records the staged snapshot.',
    why: 'Working tree → staging area → commit is the core Git mental model.',
    task: 'Stage src/pipeline.py and commit it with message `Add bronze pipeline`.',
    starter: '# Stage then commit\n',
    solution: 'git add src/pipeline.py\ngit commit -m "Add bronze pipeline"',
    hints: ['Add the file first.', 'Use `-m` for a commit message.'],
    pitfall: 'After editing a staged file again, stage it again if you want the newer content included.',
  }),
  L({
    id: 'git-branch', track: 'git', level: 'Intermediate', language: 'shell', title: 'Create and switch to a feature branch',
    concept: 'Branches are movable references to commits that let you isolate work.',
    why: 'Feature branches make changes reviewable and reversible.',
    task: 'Create and switch to branch `feature/scd2` using modern Git syntax.',
    starter: '# One command\n',
    solution: 'git switch -c feature/scd2',
    hints: ['`switch -c` creates then switches.'],
    pitfall: 'Commit or intentionally preserve your local changes before switching contexts when changes could conflict.',
  }),
  L({
    id: 'git-restore', track: 'git', level: 'Intermediate', language: 'shell', title: 'Unstage without deleting working changes',
    concept: '`git restore --staged` removes a path from the staging area while keeping the working-tree edit.',
    why: 'This is a safe correction when you staged the wrong file.',
    task: 'Unstage config.yaml but keep your edits in the file.',
    starter: '# Git command\n',
    solution: 'git restore --staged config.yaml',
    hints: ['The important flag is `--staged`.'],
    pitfall: '`git restore config.yaml` without `--staged` can discard working-tree changes, so read the command carefully.',
  }),
  L({
    id: 'git-sync', track: 'git', level: 'Expert', language: 'shell', title: 'Update before pushing',
    concept: 'A typical collaborative workflow fetches/integrates remote changes before pushing local commits.',
    why: 'You should recognize when a push rejection means the remote branch has moved.',
    task: 'Write a cautious sequence to inspect status, pull the current branch with rebase, then push.',
    starter: '# Three commands\n',
    solution: 'git status\ngit pull --rebase\ngit push',
    hints: ['Inspect first.', 'Rebase can keep a linear local feature-branch history when appropriate.'],
    pitfall: 'Do not mechanically rebase shared/public branch history. Follow the repository’s collaboration policy.',
  }),

  // CRON
  L({
    id: 'cron-fields', track: 'cron', level: 'Beginner', language: 'shell', title: 'Read the five cron fields',
    concept: 'Classic crontab timing fields are minute, hour, day-of-month, month, day-of-week, followed by the command.',
    why: 'The syntax is compact enough that many engineers misread it under pressure.',
    task: 'Write a cron expression that runs every day at 06:30.',
    starter: '# minute hour day month weekday command\n',
    solution: '30 6 * * * /usr/bin/python3 /opt/etl/job.py',
    hints: ['Minute = 30, hour = 6.', 'Asterisk means every allowed value.'],
    pitfall: 'Cron runs with a limited environment; use absolute paths for executables/files when practical.',
  }),
  L({
    id: 'cron-weekdays', track: 'cron', level: 'Intermediate', language: 'shell', title: 'Weekday ETL with logs',
    concept: 'Ranges select multiple field values; shell redirection captures stdout and stderr.',
    why: 'A scheduled job is hard to operate if its output disappears.',
    task: 'Run job.py at 07:00 Monday-Friday and append stdout+stderr to /var/log/etl.log.',
    starter: '# Write the crontab line\n',
    solution: '0 7 * * 1-5 /usr/bin/python3 /opt/etl/job.py >> /var/log/etl.log 2>&1',
    hints: ['Weekdays are commonly represented as 1-5.', '`>>` appends stdout; `2>&1` sends stderr to the same destination.'],
    pitfall: 'For critical production workflows, a proper orchestrator usually gives better retries, dependencies, observability, and backfill semantics than cron alone.',
  }),

  // DOCKER
  L({
    id: 'dk-build', track: 'docker', level: 'Beginner', language: 'shell', title: 'Build an image',
    concept: 'An image is an immutable template; a container is a running/stopped instance created from an image.',
    why: 'This distinction is the first Docker concept to make automatic.',
    task: 'Build the Dockerfile in the current directory and tag the image `etl-job:dev`.',
    starter: '# docker build command\n',
    solution: 'docker build -t etl-job:dev .',
    hints: ['`-t` sets the tag.', '`.` is the build context.'],
    pitfall: 'The build context can accidentally include large or sensitive files; use a suitable `.dockerignore`.',
  }),
  L({
    id: 'dk-run', track: 'docker', level: 'Beginner', language: 'shell', title: 'Run a one-off container',
    concept: '`docker run` creates and starts a container from an image.',
    why: 'One-off batch containers are common for data utilities and local testing.',
    task: 'Run etl-job:dev and remove the container automatically when it exits.',
    starter: '# docker run command\n',
    solution: 'docker run --rm etl-job:dev',
    hints: ['Use `--rm` for disposable containers.'],
    pitfall: 'Removing the container does not remove the image.',
  }),
  L({
    id: 'dk-inspect', track: 'docker', level: 'Intermediate', language: 'shell', title: 'Inspect running containers and logs',
    concept: '`docker ps` lists running containers; `docker logs` reads a container’s captured logs.',
    why: 'These are first-response troubleshooting commands.',
    task: 'List running containers, then show logs for a container named etl-worker.',
    starter: '# Two commands\n',
    solution: 'docker ps\ndocker logs etl-worker',
    hints: ['Container name or ID can be used with logs.'],
    pitfall: 'Logs only show what the process writes to stdout/stderr unless logging is configured differently.',
  }),
  L({
    id: 'dk-dockerfile', track: 'docker', level: 'Intermediate', language: 'dockerfile', title: 'Minimal Python Dockerfile',
    concept: 'A Dockerfile defines the filesystem and default command for an image layer by layer.',
    why: 'You should recognize FROM, WORKDIR, COPY, RUN, and CMD without needing to memorize advanced container internals.',
    task: 'Complete a minimal image that copies requirements.txt, installs dependencies, copies job.py, and runs it.',
    starter: 'FROM python:3.12-slim\nWORKDIR /app\n\n# copy requirements and install\n# copy job.py\n# run job.py\n',
    solution: 'FROM python:3.12-slim\nWORKDIR /app\n\nCOPY requirements.txt .\nRUN pip install --no-cache-dir -r requirements.txt\nCOPY job.py .\n\nCMD ["python", "job.py"]',
    hints: ['Install requirements before copying frequently changing app code to improve layer caching.', 'JSON-array CMD avoids shell parsing.'],
    pitfall: 'Do not bake credentials into image layers.',
  }),

  // KUBERNETES
  L({
    id: 'k8-get', track: 'kubernetes', level: 'Beginner', language: 'shell', title: 'List pods',
    concept: 'A Pod is Kubernetes’ basic unit for running one or more tightly coupled containers.',
    why: 'The first troubleshooting question is often: is the workload running, pending, restarting, or failed?',
    task: 'List pods in the current namespace with extra details.',
    starter: '# kubectl command\n',
    solution: 'kubectl get pods -o wide',
    hints: ['Use `get pods` and wide output.'],
    pitfall: 'If you do not specify a namespace, kubectl uses the current namespace from your context.',
  }),
  L({
    id: 'k8-logs', track: 'kubernetes', level: 'Intermediate', language: 'shell', title: 'Describe and read pod logs',
    concept: '`describe` shows resource state/events; `logs` shows application output.',
    why: 'Together they separate scheduling/configuration problems from application-runtime problems.',
    task: 'Describe pod etl-worker-abc, then show its logs.',
    starter: '# Two commands\n',
    solution: 'kubectl describe pod etl-worker-abc\nkubectl logs etl-worker-abc',
    hints: ['Use the resource type with describe.', 'Logs can use the pod name directly.'],
    pitfall: 'Multi-container pods may require `-c <container-name>` when reading logs.',
  }),
  L({
    id: 'k8-context', track: 'kubernetes', level: 'Intermediate', language: 'shell', title: 'Check cluster context before acting',
    concept: 'kubectl context determines which cluster/user/namespace your commands target.',
    why: 'Accidental operations against the wrong cluster are an avoidable production risk.',
    task: 'Show the current context, then list all configured contexts.',
    starter: '# Two commands\n',
    solution: 'kubectl config current-context\nkubectl config get-contexts',
    hints: ['Both commands live under `kubectl config`.'],
    pitfall: 'Always verify context/namespace before applying or deleting resources in environments you do not use constantly.',
  }),
  L({
    id: 'k8-apply', track: 'kubernetes', level: 'Expert', language: 'shell', title: 'Apply declarative YAML',
    concept: '`kubectl apply -f` reconciles declared resource configuration from a file.',
    why: 'Declarative configuration is more repeatable than a long sequence of imperative commands.',
    task: 'Apply k8s/deployment.yaml.',
    starter: '# kubectl command\n',
    solution: 'kubectl apply -f k8s/deployment.yaml',
    hints: ['Use `apply -f`.'],
    pitfall: 'In mature environments, GitOps/CI/CD usually controls cluster changes; manual apply may be restricted.',
  }),

  // CLOUD CLI
  L({
    id: 'cl-azure', track: 'cloud', level: 'Beginner', language: 'shell', title: 'Azure CLI: login and inspect subscription',
    concept: '`az` is the Azure CLI command family. Authentication and subscription context determine which resources commands target.',
    why: 'You should be able to authenticate interactively and confirm where you are before running resource commands.',
    task: 'Write commands to sign in and then show the active Azure account/subscription.',
    starter: '# Two Azure CLI commands\n',
    solution: 'az login\naz account show',
    hints: ['Authentication command is `az login`.', 'Account commands are under `az account`.'],
    pitfall: 'For automation, prefer service principals, workload identity, or managed identity rather than interactive user login.',
  }),
  L({
    id: 'cl-azure-set', track: 'cloud', level: 'Intermediate', language: 'shell', title: 'Azure CLI: set subscription context',
    concept: 'Azure accounts may have access to multiple subscriptions; commands run against the active one unless explicitly scoped.',
    why: 'Context mistakes can lead to operating on the wrong environment.',
    task: 'Set the active subscription to `00000000-0000-0000-0000-000000000000`.',
    starter: '# Azure CLI command\n',
    solution: 'az account set --subscription 00000000-0000-0000-0000-000000000000',
    hints: ['Use `az account set --subscription`.'],
    pitfall: 'Use placeholders in training; never publish real tenant/subscription identifiers from private environments unnecessarily.',
  }),
  L({
    id: 'cl-gcp', track: 'cloud', level: 'Beginner', language: 'shell', title: 'GCP CLI: login and set project',
    concept: '`gcloud` is the Google Cloud CLI. User authentication and active project are separate pieces of context.',
    why: 'Cloud CLIs look similar conceptually but use different command syntax.',
    task: 'Authenticate interactively, then set project to `de-lab-project`.',
    starter: '# Two gcloud commands\n',
    solution: 'gcloud auth login\ngcloud config set project de-lab-project',
    hints: ['Auth commands live under `gcloud auth`.', 'Project context is set through `gcloud config`.'],
    pitfall: 'Do not use interactive user credentials as the default pattern for unattended production workloads.',
  }),
  L({
    id: 'cl-fabric-install', track: 'cloud', level: 'Beginner', language: 'shell', title: 'Fabric CLI: install, login, list workspaces',
    concept: 'The Microsoft Fabric CLI command is `fab`; it can browse workspaces/items and automate Fabric operations.',
    why: 'This gives you a terminal bridge into Fabric rather than treating Fabric as UI-only.',
    task: 'Install Fabric CLI with pip, authenticate interactively, then list accessible workspaces.',
    starter: '# Three commands\n',
    solution: 'pip install ms-fabric-cli\nfab auth login\nfab ls',
    hints: ['Package: `ms-fabric-cli`.', 'CLI command: `fab`.'],
    pitfall: 'For CI/CD, use an organization-approved non-interactive identity rather than a personal interactive login.',
  }),
  L({
    id: 'cl-recognize', track: 'cloud', level: 'Expert', language: 'shell', title: 'Recognize command families instantly',
    concept: 'A useful beginner goal is not memorizing every flag—it is recognizing which CLI owns the task and how to ask it for help.',
    why: 'Real work involves documentation and `--help`; fluency means navigating a command tree without panic.',
    task: 'Write one help command for Azure CLI, gcloud, Fabric CLI, Docker, and kubectl.',
    starter: '# One help command per tool\n',
    solution: 'az --help\ngcloud --help\nfab --help\ndocker --help\nkubectl --help',
    hints: ['Most CLIs support `--help`.'],
    pitfall: 'Do not memorize destructive commands. Learn inspection/help/context commands first.',
  }),

  // GATEWAY
  L({
    id: 'gw-architecture', track: 'gateway', level: 'Beginner', language: 'powershell', title: 'Gateway architecture: what runs where?',
    concept: 'The standard on-premises data gateway is installed on a supported Windows machine and bridges private-network data sources to Microsoft cloud services using outbound connectivity.',
    why: 'The conceptual architecture matters more than memorizing installer screens.',
    task: 'Write comments identifying the three sides: Power BI/Fabric cloud service, Windows gateway VM, and private SQL data source.',
    starter: '# Fill the three architecture lines as comments\n',
    solution: '# Cloud: Power BI / Fabric service\n# Bridge: Windows VM running standard on-premises data gateway\n# Private source: SQL Server or other supported data source reachable from the VM',
    hints: ['Think cloud → gateway bridge → data source.', 'The VM must be able to reach the data source.'],
    pitfall: 'The gateway is not a database and does not normally require inbound internet ports to expose the source publicly.',
  }),
  L({
    id: 'gw-preflight', track: 'gateway', level: 'Intermediate', language: 'powershell', title: 'Gateway VM preflight checks',
    concept: 'Before blaming Power BI, verify the Windows VM is online, the gateway service is running, and the database endpoint is reachable.',
    why: 'Troubleshooting is faster when you test from the gateway machine itself.',
    task: 'Write PowerShell commands to find gateway-related services and test SQL host sql.internal.local on TCP 1433.',
    starter: '# Inspect services and test SQL connectivity\n',
    solution: 'Get-Service | Where-Object { $_.DisplayName -like "*gateway*" }\nTest-NetConnection -ComputerName sql.internal.local -Port 1433',
    hints: ['Use Get-Service and Where-Object.', 'Use Test-NetConnection for the TCP check.'],
    pitfall: 'Network reachability is only one layer; also verify drivers, data-source mapping, credentials, and gateway version.',
  }),
  L({
    id: 'gw-checklist', track: 'gateway', level: 'Expert', language: 'plaintext', title: 'Install/configuration checklist',
    concept: 'A reliable gateway deployment separates machine readiness, installation, registration, data-source configuration, and operations.',
    why: 'This is what you need in an interview: explain the sequence and where failures can happen.',
    task: 'Write the 6 major steps you would follow to deploy a standard gateway on a Windows VM.',
    starter: '1.\n2.\n3.\n4.\n5.\n6.\n',
    solution: '1. Prepare a supported, always-on Windows VM close to the data source and verify outbound connectivity.\n2. Install any required database drivers/providers on the VM.\n3. Install the latest standard on-premises data gateway as a machine administrator.\n4. Sign in with the organization work/school account and register a new gateway or join a gateway cluster.\n5. In the Power BI/Fabric service, configure the gateway connection/data source and credentials, then map the semantic model/dataflow.\n6. Test refresh/query, inspect logs and service health, keep the gateway updated, and use a cluster when high availability is required.',
    hints: ['Think machine → drivers → install → register → map → operate.', 'Standard mode is the general shared/enterprise mode.'],
    pitfall: 'Do not install a production gateway on a laptop that sleeps or disconnects. Treat the gateway VM as infrastructure.',
  }),
]

export const levelOrder = ['Beginner', 'Intermediate', 'Expert']

export const sourceLinks = [
  { label: 'Monaco Editor', url: 'https://microsoft.github.io/monaco-editor/', note: 'VS Code editor engine used for the practice workspace.' },
  { label: 'JupyterLite', url: 'https://jupyterlite.readthedocs.io/en/stable/', note: 'Optional future in-browser notebook execution with Pyodide.' },
  { label: 'Tabular Editor C# scripting', url: 'https://docs.tabulareditor.com/en/features/csharp-scripts.html', note: 'Model / Selected scripting concepts and C# examples.' },
  { label: 'Apache Airflow', url: 'https://airflow.apache.org/docs/apache-airflow/stable/', note: 'Current DAG authoring and scheduling reference.' },
  { label: 'Python tutorial', url: 'https://docs.python.org/3/tutorial/', note: 'Functions, control flow, lists, data structures, and lambda expressions.' },
  { label: 'Python functional programming', url: 'https://docs.python.org/3/howto/functional.html', note: 'Iterators, generators, small functions, lambda, map/filter concepts.' },
  { label: 'pandas', url: 'https://pandas.pydata.org/docs/', note: 'DataFrame, merge, groupby, transform, rank, rolling, and reshape reference.' },
  { label: 'PySpark', url: 'https://spark.apache.org/docs/latest/api/python/', note: 'Spark DataFrame, joins, groupBy, functions, and Window API.' },
  { label: 'DuckDB SQL', url: 'https://duckdb.org/docs/current/sql/introduction', note: 'SQL reference for the uploaded notebook/source-style dialect.' },
  { label: 'DuckDB QUALIFY', url: 'https://duckdb.org/docs/current/sql/query_syntax/qualify', note: 'Window-result filtering used in dialect comparisons.' },
  { label: 'BigQuery GoogleSQL', url: 'https://cloud.google.com/bigquery/docs/reference/standard-sql/query-syntax', note: 'GoogleSQL joins, GROUP BY, QUALIFY, GROUPING SETS, ROLLUP, CUBE, and query syntax.' },
  { label: 'BigQuery arrays', url: 'https://cloud.google.com/bigquery/docs/arrays', note: 'ARRAY, STRUCT, and UNNEST patterns used by the BigQuery exercises.' },
  { label: 'DAX', url: 'https://learn.microsoft.com/en-us/dax/', note: 'Microsoft DAX reference.' },
  { label: 'T-SQL GROUP BY / GROUPING SETS', url: 'https://learn.microsoft.com/en-us/sql/t-sql/queries/select-group-by-transact-sql', note: 'Microsoft reference for GROUP BY, GROUPING SETS, ROLLUP, and CUBE.' },
  { label: 'T-SQL CASE', url: 'https://learn.microsoft.com/en-us/sql/t-sql/language-elements/case-transact-sql', note: 'Microsoft reference for conditional CASE expressions.' },
  { label: 'T-SQL window functions', url: 'https://learn.microsoft.com/en-us/sql/t-sql/queries/select-over-clause-transact-sql', note: 'Microsoft reference for OVER, PARTITION BY, ORDER BY, and window frames.' },
  { label: 'T-SQL ROW_NUMBER', url: 'https://learn.microsoft.com/en-us/sql/t-sql/functions/row-number-transact-sql', note: 'Microsoft ranking-function reference used by the SQL Challenge Lab.' },
  { label: 'Git', url: 'https://git-scm.com/docs', note: 'Official Git command documentation.' },
  { label: 'Docker CLI', url: 'https://docs.docker.com/reference/cli/docker/', note: 'Docker commands and options.' },
  { label: 'kubectl', url: 'https://kubernetes.io/docs/reference/kubectl/', note: 'Kubernetes CLI reference.' },
  { label: 'Azure CLI', url: 'https://learn.microsoft.com/en-us/cli/azure/', note: 'Azure command-line reference.' },
  { label: 'Google Cloud CLI', url: 'https://cloud.google.com/sdk/docs', note: 'gcloud installation/auth/configuration.' },
  { label: 'Fabric CLI', url: 'https://microsoft.github.io/fabric-cli/', note: 'Microsoft Fabric `fab` CLI.' },
  { label: 'Power BI gateway', url: 'https://learn.microsoft.com/en-us/data-integration/gateway/service-gateway-install', note: 'Gateway requirements and installation.' },
]
