export const engineDefinitions = {
  tsql: { label: 'T-SQL', language: 'sql', family: 'SQL' },
  duckdb: { label: 'DuckDB', language: 'sql', family: 'SQL' },
  bigquery: { label: 'BigQuery', language: 'sql', family: 'SQL' },
  pandas: { label: 'pandas', language: 'python', family: 'DataFrame' },
  pyspark: { label: 'PySpark', language: 'python', family: 'DataFrame' },
}

export const engineTopics = [
  { id: 'eng-transfer', name: 'Cross-engine patterns', short: 'Translate', icon: '⇄', description: 'Solve the same data transformation in SQL, pandas, and PySpark.' },
  { id: 'eng-bigquery', name: 'BigQuery essentials', short: 'BigQuery', icon: 'BQ', description: 'GoogleSQL patterns worth knowing: QUALIFY, arrays, UNNEST, SAFE_DIVIDE, and partition-friendly filters.' },
  { id: 'eng-pyspark', name: 'PySpark essentials', short: 'PySpark', icon: 'SP', description: 'Distributed DataFrame syntax: columns, joins, windows, explode, repartitioning, and broadcast hints.' },
  { id: 'eng-pandas', name: 'pandas essentials', short: 'pandas', icon: 'PD', description: 'Practical local DataFrame fluency: merge, groupby, transform, rank, explode, and validation.' },
]

const V = (language, starter, solution, explanation) => ({ language, starter, solution, explanation })
const E = (x) => ({ collection: 'engine-lab', why: 'Translate one data-engineering idea across tools until the operation feels familiar even when the syntax changes.', ...x })

export const engineChallenges = [
  E({ id:'eng-filter-active', track:'eng-transfer', level:'Beginner', title:'Filter active records', concept:'Filtering keeps rows that satisfy a boolean condition.', context:'Dataset orders has order_id, customer_id, status, amount. Keep only status = ACTIVE.', task:'Write the filter in the selected engine.', hints:['Find the row-filter operation for the selected engine.','The condition is status equals ACTIVE.'], pitfall:'Do not confuse row filtering with selecting columns.', variants:{
    tsql: V('sql', `SELECT *\nFROM dbo.orders\nWHERE -- condition\n`, `SELECT *\nFROM dbo.orders\nWHERE status = 'ACTIVE';`, 'T-SQL filters rows with WHERE.'),
    duckdb: V('sql', `SELECT *\nFROM orders\nWHERE -- condition\n`, `SELECT *\nFROM orders\nWHERE status = 'ACTIVE';`, 'The standard WHERE pattern is identical in DuckDB.'),
    bigquery: V('sql', `SELECT *\nFROM orders\nWHERE -- condition\n`, `SELECT *\nFROM orders\nWHERE status = 'ACTIVE';`, 'GoogleSQL uses the same WHERE pattern.'),
    pandas: V('python', `active = df[\n    # boolean mask\n]\n`, `active = df[df["status"] == "ACTIVE"]`, 'A pandas boolean Series is used as a mask.'),
    pyspark: V('python', `from pyspark.sql import functions as F\n\nactive = df.filter(\n    # Column expression\n)`, `from pyspark.sql import functions as F\n\nactive = df.filter(F.col("status") == "ACTIVE")`, 'PySpark filter expects a distributed Column expression.'),
  }}),
  E({ id:'eng-derived-flag', track:'eng-transfer', level:'Beginner', title:'Create a high-value flag', concept:'Conditional logic derives a new value without filtering rows.', context:'orders has amount. Create is_high_value = 1 when amount >= 1000, otherwise 0.', task:'Add the conditional column in the selected engine.', hints:['Think CASE in SQL.','Think where/when in DataFrame APIs.'], pitfall:'A filter would remove low-value rows; the task is to keep them and label them.', variants:{
    tsql: V('sql', `SELECT *,\n       CASE\n           -- condition\n       END AS is_high_value\nFROM dbo.orders;`, `SELECT *,\n       CASE WHEN amount >= 1000 THEN 1 ELSE 0 END AS is_high_value\nFROM dbo.orders;`, 'CASE returns one scalar value for each row.'),
    duckdb: V('sql', `SELECT *,\n       CASE WHEN -- THEN 1 ELSE 0 END AS is_high_value\nFROM orders;`, `SELECT *,\n       CASE WHEN amount >= 1000 THEN 1 ELSE 0 END AS is_high_value\nFROM orders;`, 'DuckDB uses standard CASE syntax.'),
    bigquery: V('sql', `SELECT *,\n       IF(-- condition, 1, 0) AS is_high_value\nFROM orders;`, `SELECT *,\n       IF(amount >= 1000, 1, 0) AS is_high_value\nFROM orders;`, 'BigQuery supports both CASE and the compact IF(condition, true, false) function.'),
    pandas: V('python', `import numpy as np\n\ndf["is_high_value"] = np.where(\n    # condition, true, false\n)`, `import numpy as np\n\ndf["is_high_value"] = np.where(df["amount"] >= 1000, 1, 0)`, 'np.where vectorizes a simple two-way conditional.'),
    pyspark: V('python', `from pyspark.sql import functions as F\n\ndf = df.withColumn(\n    "is_high_value",\n    F.when(# condition, 1).otherwise(0)\n)`, `from pyspark.sql import functions as F\n\ndf = df.withColumn(\n    "is_high_value",\n    F.when(F.col("amount") >= 1000, 1).otherwise(0)\n)`, 'withColumn plus when/otherwise is the standard PySpark pattern.'),
  }}),
  E({ id:'eng-group-sum', track:'eng-transfer', level:'Beginner', title:'Revenue by customer', concept:'Group rows by a business key and aggregate each group.', context:'orders(customer_id, amount).', task:'Return total amount per customer.', hints:['Group by customer_id.','Sum amount.'], pitfall:'Do not include row-level columns that are neither grouped nor aggregated.', variants:{
    tsql: V('sql', `SELECT customer_id,\n       -- total\nFROM dbo.orders\nGROUP BY -- key\n`, `SELECT customer_id, SUM(amount) AS total_amount\nFROM dbo.orders\nGROUP BY customer_id;`, 'GROUP BY changes the grain to one row per customer.'),
    duckdb: V('sql', `SELECT customer_id, -- total\nFROM orders\nGROUP BY customer_id;`, `SELECT customer_id, SUM(amount) AS total_amount\nFROM orders\nGROUP BY customer_id;`, 'Standard aggregation syntax transfers directly.'),
    bigquery: V('sql', `SELECT customer_id, -- total\nFROM orders\nGROUP BY customer_id;`, `SELECT customer_id, SUM(amount) AS total_amount\nFROM orders\nGROUP BY customer_id;`, 'GoogleSQL uses the same core GROUP BY pattern.'),
    pandas: V('python', `result = (\n    df.groupby(# key, as_index=False)\n      .agg(# named aggregation)\n)`, `result = (\n    df.groupby("customer_id", as_index=False)\n      .agg(total_amount=("amount", "sum"))\n)`, 'Named aggregation keeps the result column explicit and readable.'),
    pyspark: V('python', `from pyspark.sql import functions as F\n\nresult = (\n    df.groupBy(# key)\n      .agg(# aggregation)\n)`, `from pyspark.sql import functions as F\n\nresult = (\n    df.groupBy("customer_id")\n      .agg(F.sum("amount").alias("total_amount"))\n)`, 'groupBy returns GroupedData; agg performs distributed aggregation.'),
  }}),
  E({ id:'eng-multi-agg', track:'eng-transfer', level:'Intermediate', title:'Order count, revenue, and average by customer', concept:'One grouping operation can compute several metrics at the same grain.', context:'orders(customer_id, order_id, amount).', task:'Return order_count, total_amount, and avg_amount per customer.', hints:['All metrics use the same grouping key.','Use count, sum and average.'], pitfall:'Running three separate group operations creates needless work and makes joining results necessary.', variants:{
    tsql: V('sql', `SELECT customer_id,\n       -- three aggregates\nFROM dbo.orders\nGROUP BY customer_id;`, `SELECT customer_id,\n       COUNT(*) AS order_count,\n       SUM(amount) AS total_amount,\n       AVG(amount) AS avg_amount\nFROM dbo.orders\nGROUP BY customer_id;`, 'All aggregates are evaluated at the customer grain.'),
    duckdb: V('sql', `SELECT customer_id, -- aggregates\nFROM orders\nGROUP BY customer_id;`, `SELECT customer_id, COUNT(*) AS order_count, SUM(amount) AS total_amount, AVG(amount) AS avg_amount\nFROM orders\nGROUP BY customer_id;`, 'DuckDB uses the same standard aggregate functions.'),
    bigquery: V('sql', `SELECT customer_id, -- aggregates\nFROM orders\nGROUP BY customer_id;`, `SELECT customer_id, COUNT(*) AS order_count, SUM(amount) AS total_amount, AVG(amount) AS avg_amount\nFROM orders\nGROUP BY customer_id;`, 'The aggregation pattern is portable to BigQuery.'),
    pandas: V('python', `result = df.groupby("customer_id", as_index=False).agg(\n    # metrics\n)`, `result = df.groupby("customer_id", as_index=False).agg(\n    order_count=("order_id", "size"),\n    total_amount=("amount", "sum"),\n    avg_amount=("amount", "mean"),\n)`, 'pandas named aggregation maps output names to source-column/function pairs.'),
    pyspark: V('python', `from pyspark.sql import functions as F\nresult = df.groupBy("customer_id").agg(\n    # metrics\n)`, `from pyspark.sql import functions as F\nresult = df.groupBy("customer_id").agg(\n    F.count("*").alias("order_count"),\n    F.sum("amount").alias("total_amount"),\n    F.avg("amount").alias("avg_amount"),\n)`, 'PySpark accepts multiple aggregate expressions in a single agg call.'),
  }}),
  E({ id:'eng-inner-join', track:'eng-transfer', level:'Beginner', title:'Join orders to customers', concept:'An inner join keeps rows whose key exists on both sides.', context:'orders(customer_id, order_id, amount); customers(customer_id, customer_name).', task:'Attach customer_name to matching orders.', hints:['customer_id is the join key.','Use an inner join / merge.'], pitfall:'Joining on the wrong key can multiply rows or silently mismatch records.', variants:{
    tsql: V('sql', `SELECT o.*, c.customer_name\nFROM dbo.orders AS o\nINNER JOIN dbo.customers AS c\n    ON -- key\n`, `SELECT o.*, c.customer_name\nFROM dbo.orders AS o\nINNER JOIN dbo.customers AS c\n    ON o.customer_id = c.customer_id;`, 'The ON predicate determines which row pairs match.'),
    duckdb: V('sql', `SELECT o.*, c.customer_name\nFROM orders o\nJOIN customers c\n    ON -- key\n`, `SELECT o.*, c.customer_name\nFROM orders o\nJOIN customers c\n    ON o.customer_id = c.customer_id;`, 'JOIN without a modifier means INNER JOIN.'),
    bigquery: V('sql', `SELECT o.*, c.customer_name\nFROM orders o\nJOIN customers c\n  ON -- key\n`, `SELECT o.*, c.customer_name\nFROM orders o\nJOIN customers c\n  ON o.customer_id = c.customer_id;`, 'GoogleSQL supports ON and USING join conditions.'),
    pandas: V('python', `result = orders.merge(\n    customers[["customer_id", "customer_name"]],\n    # join arguments\n)`, `result = orders.merge(\n    customers[["customer_id", "customer_name"]],\n    on="customer_id",\n    how="inner",\n)`, 'DataFrame.merge is the database-style column join in pandas.'),
    pyspark: V('python', `result = orders.join(\n    customers.select("customer_id", "customer_name"),\n    # key and join type\n)`, `result = orders.join(\n    customers.select("customer_id", "customer_name"),\n    on="customer_id",\n    how="inner",\n)`, 'PySpark DataFrame.join can join directly by a shared key name.'),
  }}),
  E({ id:'eng-anti-join', track:'eng-transfer', level:'Intermediate', title:'Find orders with no customer match', concept:'An anti join returns left-side rows that have no matching key on the right.', context:'orders(customer_id,...); customers(customer_id,...).', task:'Return orders whose customer_id is not present in customers.', hints:['In SQL you can left join and test right-side NULL, or use NOT EXISTS.','PySpark has left_anti directly.'], pitfall:'NOT IN can behave unexpectedly when the right side contains NULL.', variants:{
    tsql: V('sql', `SELECT o.*\nFROM dbo.orders AS o\nWHERE NOT EXISTS (\n    SELECT 1\n    FROM dbo.customers AS c\n    WHERE -- key\n);`, `SELECT o.*\nFROM dbo.orders AS o\nWHERE NOT EXISTS (\n    SELECT 1\n    FROM dbo.customers AS c\n    WHERE c.customer_id = o.customer_id\n);`, 'NOT EXISTS expresses anti-join intent without NULL ambiguity.'),
    duckdb: V('sql', `SELECT o.*\nFROM orders o\nANTI JOIN customers c\n    ON -- key\n`, `SELECT o.*\nFROM orders o\nANTI JOIN customers c\n    ON o.customer_id = c.customer_id;`, 'DuckDB supports an explicit ANTI JOIN form.'),
    bigquery: V('sql', `SELECT o.*\nFROM orders o\nWHERE NOT EXISTS (\n  SELECT 1 FROM customers c WHERE -- key\n);`, `SELECT o.*\nFROM orders o\nWHERE NOT EXISTS (\n  SELECT 1 FROM customers c WHERE c.customer_id = o.customer_id\n);`, 'NOT EXISTS is a clear portable anti-join pattern in GoogleSQL.'),
    pandas: V('python', `merged = orders.merge(\n    customers[["customer_id"]],\n    on="customer_id", how="left", indicator=True\n)\nresult = merged[\n    # left-only rows\n]`, `merged = orders.merge(\n    customers[["customer_id"]],\n    on="customer_id", how="left", indicator=True\n)\nresult = merged[merged["_merge"] == "left_only"].drop(columns="_merge")`, 'The merge indicator reveals whether each row matched the right side.'),
    pyspark: V('python', `result = orders.join(\n    customers.select("customer_id"),\n    on="customer_id",\n    how=# anti join type\n)`, `result = orders.join(\n    customers.select("customer_id"),\n    on="customer_id",\n    how="left_anti",\n)`, 'left_anti is a first-class PySpark join type and is ideal for data-quality checks.'),
  }}),
  E({ id:'eng-latest-row', track:'eng-transfer', level:'Intermediate', title:'Latest record per customer', concept:'Rank rows inside each key by timestamp and keep the most recent one.', context:'customer_history(customer_id, updated_at, status).', task:'Return one latest row for each customer.', hints:['Partition/group by customer_id.','Sort updated_at descending.'], pitfall:'Without a tie-breaker, equal timestamps can make the chosen row nondeterministic.', variants:{
    tsql: V('sql', `WITH ranked AS (\n  SELECT *, ROW_NUMBER() OVER (\n    PARTITION BY customer_id\n    ORDER BY updated_at DESC\n  ) AS rn\n  FROM dbo.customer_history\n)\nSELECT * FROM ranked WHERE --\n`, `WITH ranked AS (\n  SELECT *, ROW_NUMBER() OVER (\n    PARTITION BY customer_id\n    ORDER BY updated_at DESC\n  ) AS rn\n  FROM dbo.customer_history\n)\nSELECT * FROM ranked WHERE rn = 1;`, 'T-SQL computes the window first and filters it in an outer query.'),
    duckdb: V('sql', `SELECT *\nFROM customer_history\nQUALIFY ROW_NUMBER() OVER (\n  PARTITION BY customer_id ORDER BY updated_at DESC\n) = --\n`, `SELECT *\nFROM customer_history\nQUALIFY ROW_NUMBER() OVER (\n  PARTITION BY customer_id ORDER BY updated_at DESC\n) = 1;`, 'DuckDB QUALIFY filters window results in the same query.'),
    bigquery: V('sql', `SELECT *\nFROM customer_history\nQUALIFY ROW_NUMBER() OVER (\n  PARTITION BY customer_id ORDER BY updated_at DESC\n) = --\n`, `SELECT *\nFROM customer_history\nQUALIFY ROW_NUMBER() OVER (\n  PARTITION BY customer_id ORDER BY updated_at DESC\n) = 1;`, 'BigQuery also supports QUALIFY.'),
    pandas: V('python', `latest = (\n    df.sort_values(# sort columns)\n      .drop_duplicates(# key, keep=#)\n)`, `latest = (\n    df.sort_values(["customer_id", "updated_at"])\n      .drop_duplicates("customer_id", keep="last")\n)`, 'Sorting then keeping the last row is a compact pandas equivalent.'),
    pyspark: V('python', `from pyspark.sql import functions as F\nfrom pyspark.sql.window import Window\n\nw = Window.partitionBy(#).orderBy(#)\nlatest = (df.withColumn("rn", F.row_number().over(w))\n            .filter(#)\n            .drop("rn"))`, `from pyspark.sql import functions as F\nfrom pyspark.sql.window import Window\n\nw = Window.partitionBy("customer_id").orderBy(F.col("updated_at").desc())\nlatest = (df.withColumn("rn", F.row_number().over(w))\n            .filter(F.col("rn") == 1)\n            .drop("rn"))`, 'PySpark uses a WindowSpec plus row_number, mirroring the SQL mental model.'),
  }}),
  E({ id:'eng-running-total', track:'eng-transfer', level:'Intermediate', title:'Running revenue by customer', concept:'A running total aggregates from the start of each partition through the current row.', context:'orders(customer_id, order_date, order_id, amount).', task:'Add running_amount ordered by date for each customer.', hints:['Partition by customer.','Order by date plus a stable tie-breaker.'], pitfall:'Omitting a tie-breaker can make row-by-row results unstable on duplicate dates.', variants:{
    tsql: V('sql', `SELECT *,\n  SUM(amount) OVER (\n    PARTITION BY customer_id\n    ORDER BY order_date, order_id\n    ROWS BETWEEN --\n  ) AS running_amount\nFROM dbo.orders;`, `SELECT *,\n  SUM(amount) OVER (\n    PARTITION BY customer_id\n    ORDER BY order_date, order_id\n    ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n  ) AS running_amount\nFROM dbo.orders;`, 'ROWS makes the frame explicitly row-by-row.'),
    duckdb: V('sql', `SELECT *, SUM(amount) OVER (\n  PARTITION BY customer_id ORDER BY order_date, order_id\n  ROWS BETWEEN UNBOUNDED PRECEDING AND --\n) AS running_amount\nFROM orders;`, `SELECT *, SUM(amount) OVER (\n  PARTITION BY customer_id ORDER BY order_date, order_id\n  ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n) AS running_amount\nFROM orders;`, 'DuckDB uses the same window frame syntax.'),
    bigquery: V('sql', `SELECT *, SUM(amount) OVER (\n  PARTITION BY customer_id ORDER BY order_date, order_id\n  ROWS BETWEEN UNBOUNDED PRECEDING AND --\n) AS running_amount\nFROM orders;`, `SELECT *, SUM(amount) OVER (\n  PARTITION BY customer_id ORDER BY order_date, order_id\n  ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW\n) AS running_amount\nFROM orders;`, 'GoogleSQL supports ROWS window frames.'),
    pandas: V('python', `ordered = df.sort_values([#])\nordered["running_amount"] = (\n    ordered.groupby(#)["amount"].#\n)`, `ordered = df.sort_values(["customer_id", "order_date", "order_id"])\nordered["running_amount"] = (\n    ordered.groupby("customer_id")["amount"].cumsum()\n)`, 'groupby + cumsum is the pandas running-total pattern.'),
    pyspark: V('python', `from pyspark.sql import functions as F\nfrom pyspark.sql.window import Window\n\nw = (Window.partitionBy("customer_id")\n     .orderBy("order_date", "order_id")\n     .rowsBetween(#, #))\nresult = df.withColumn("running_amount", F.sum("amount").over(w))`, `from pyspark.sql import functions as F\nfrom pyspark.sql.window import Window\n\nw = (Window.partitionBy("customer_id")\n     .orderBy("order_date", "order_id")\n     .rowsBetween(Window.unboundedPreceding, Window.currentRow))\nresult = df.withColumn("running_amount", F.sum("amount").over(w))`, 'rowsBetween mirrors SQL ROWS BETWEEN semantics.'),
  }}),
  E({ id:'eng-lag-delta', track:'eng-transfer', level:'Intermediate', title:'Compare each amount with the previous order', concept:'Lag brings a prior row value into the current row for change calculations.', context:'orders(customer_id, order_date, order_id, amount).', task:'Add previous_amount within customer order and calculate amount_delta.', hints:['Order within each customer.','Compute previous value before subtracting.'], pitfall:'A global shift/lag mixes different customers.', variants:{
    tsql: V('sql', `WITH x AS (\n  SELECT *, LAG(amount) OVER (\n    PARTITION BY customer_id ORDER BY order_date, order_id\n  ) AS previous_amount\n  FROM dbo.orders\n)\nSELECT *, -- delta\nFROM x;`, `WITH x AS (\n  SELECT *, LAG(amount) OVER (\n    PARTITION BY customer_id ORDER BY order_date, order_id\n  ) AS previous_amount\n  FROM dbo.orders\n)\nSELECT *, amount - previous_amount AS amount_delta\nFROM x;`, 'The first row in each customer partition naturally has NULL previous_amount.'),
    duckdb: V('sql', `SELECT *,\n  LAG(amount) OVER (PARTITION BY customer_id ORDER BY order_date, order_id) AS previous_amount\nFROM orders;`, `SELECT *,\n  LAG(amount) OVER (PARTITION BY customer_id ORDER BY order_date, order_id) AS previous_amount,\n  amount - LAG(amount) OVER (PARTITION BY customer_id ORDER BY order_date, order_id) AS amount_delta\nFROM orders;`, 'DuckDB supports standard LAG window syntax.'),
    bigquery: V('sql', `SELECT *,\n  LAG(amount) OVER (PARTITION BY customer_id ORDER BY order_date, order_id) AS previous_amount\nFROM orders;`, `SELECT *,\n  LAG(amount) OVER (PARTITION BY customer_id ORDER BY order_date, order_id) AS previous_amount,\n  amount - LAG(amount) OVER (PARTITION BY customer_id ORDER BY order_date, order_id) AS amount_delta\nFROM orders;`, 'BigQuery uses the same LAG mental model.'),
    pandas: V('python', `ordered = df.sort_values([#])\nordered["previous_amount"] = ordered.groupby(#)["amount"].#\nordered["amount_delta"] = --`, `ordered = df.sort_values(["customer_id", "order_date", "order_id"])\nordered["previous_amount"] = ordered.groupby("customer_id")["amount"].shift(1)\nordered["amount_delta"] = ordered["amount"] - ordered["previous_amount"]`, 'GroupBy.shift is the pandas analogue of LAG.'),
    pyspark: V('python', `from pyspark.sql import functions as F\nfrom pyspark.sql.window import Window\nw = Window.partitionBy("customer_id").orderBy("order_date", "order_id")\nresult = (df.withColumn("previous_amount", #)\n            .withColumn("amount_delta", #))`, `from pyspark.sql import functions as F\nfrom pyspark.sql.window import Window\nw = Window.partitionBy("customer_id").orderBy("order_date", "order_id")\nresult = (df.withColumn("previous_amount", F.lag("amount").over(w))\n            .withColumn("amount_delta", F.col("amount") - F.col("previous_amount")))`, 'F.lag over a WindowSpec mirrors SQL LAG closely.'),
  }}),
  E({ id:'eng-top-n', track:'eng-transfer', level:'Intermediate', title:'Top 3 products per category', concept:'Top-N-per-group is a ranking problem, not a global sort problem.', context:'product_sales(category, product_id, revenue).', task:'Keep the three highest-revenue products in each category.', hints:['Rank inside category.','Keep ranks <= 3.'], pitfall:'Sorting the entire dataset and taking three returns only three rows globally.', variants:{
    tsql: V('sql', `WITH ranked AS (\n  SELECT *, ROW_NUMBER() OVER (PARTITION BY category ORDER BY revenue DESC) AS rn\n  FROM dbo.product_sales\n)\nSELECT * FROM ranked WHERE --\n`, `WITH ranked AS (\n  SELECT *, ROW_NUMBER() OVER (PARTITION BY category ORDER BY revenue DESC) AS rn\n  FROM dbo.product_sales\n)\nSELECT * FROM ranked WHERE rn <= 3;`, 'T-SQL filters the computed rank in an outer query.'),
    duckdb: V('sql', `SELECT * FROM product_sales\nQUALIFY ROW_NUMBER() OVER (PARTITION BY category ORDER BY revenue DESC) <= --\n`, `SELECT * FROM product_sales\nQUALIFY ROW_NUMBER() OVER (PARTITION BY category ORDER BY revenue DESC) <= 3;`, 'QUALIFY makes top-N-per-group concise.'),
    bigquery: V('sql', `SELECT * FROM product_sales\nQUALIFY ROW_NUMBER() OVER (PARTITION BY category ORDER BY revenue DESC) <= --\n`, `SELECT * FROM product_sales\nQUALIFY ROW_NUMBER() OVER (PARTITION BY category ORDER BY revenue DESC) <= 3;`, 'BigQuery QUALIFY is ideal for this pattern.'),
    pandas: V('python', `result = (df.sort_values([#], ascending=[#, #])\n            .groupby(#, as_index=False)\n            .head(#))`, `result = (df.sort_values(["category", "revenue"], ascending=[True, False])\n            .groupby("category", as_index=False)\n            .head(3))`, 'Sort within grouping keys then take head(3) per group.'),
    pyspark: V('python', `from pyspark.sql import functions as F\nfrom pyspark.sql.window import Window\nw = Window.partitionBy("category").orderBy(F.col("revenue").desc())\nresult = df.withColumn("rn", #).filter(#)`, `from pyspark.sql import functions as F\nfrom pyspark.sql.window import Window\nw = Window.partitionBy("category").orderBy(F.col("revenue").desc())\nresult = df.withColumn("rn", F.row_number().over(w)).filter(F.col("rn") <= 3).drop("rn")`, 'This is the direct distributed equivalent of SQL ROW_NUMBER.'),
  }}),
  E({ id:'eng-null-fill', track:'eng-transfer', level:'Beginner', title:'Replace missing country with UNKNOWN', concept:'Null handling substitutes a default value while preserving rows.', context:'customers(customer_id, country) where country can be null.', task:'Create a cleaned country value where null becomes UNKNOWN.', hints:['SQL: COALESCE.','DataFrames: fillna/coalesce.'], pitfall:'The string "NULL" is not the same as an actual null value.', variants:{
    tsql: V('sql', `SELECT customer_id,\n       -- null handling AS country_clean\nFROM dbo.customers;`, `SELECT customer_id, COALESCE(country, 'UNKNOWN') AS country_clean\nFROM dbo.customers;`, 'COALESCE returns the first non-null expression.'),
    duckdb: V('sql', `SELECT customer_id, -- AS country_clean FROM customers;`, `SELECT customer_id, COALESCE(country, 'UNKNOWN') AS country_clean FROM customers;`, 'COALESCE is standard SQL.'),
    bigquery: V('sql', `SELECT customer_id, -- AS country_clean FROM customers;`, `SELECT customer_id, COALESCE(country, 'UNKNOWN') AS country_clean FROM customers;`, 'GoogleSQL supports COALESCE.'),
    pandas: V('python', `df["country_clean"] = df["country"].#`, `df["country_clean"] = df["country"].fillna("UNKNOWN")`, 'Series.fillna replaces missing values vectorially.'),
    pyspark: V('python', `from pyspark.sql import functions as F\ndf = df.withColumn("country_clean", #)`, `from pyspark.sql import functions as F\ndf = df.withColumn("country_clean", F.coalesce(F.col("country"), F.lit("UNKNOWN")))`, 'F.coalesce mirrors SQL COALESCE.'),
  }}),
  E({ id:'eng-union', track:'eng-transfer', level:'Beginner', title:'Append historical and current rows', concept:'Union/concatenation stacks compatible datasets vertically.', context:'historical_orders and current_orders have the same logical schema.', task:'Combine all rows while preserving duplicates.', hints:['Use UNION ALL rather than UNION in SQL.','Use concat/unionByName for DataFrames.'], pitfall:'UNION removes duplicates and can add unnecessary work.', variants:{
    tsql: V('sql', `SELECT * FROM dbo.historical_orders\n-- append current rows\nSELECT * FROM dbo.current_orders;`, `SELECT * FROM dbo.historical_orders\nUNION ALL\nSELECT * FROM dbo.current_orders;`, 'UNION ALL stacks rows without deduplication.'),
    duckdb: V('sql', `SELECT * FROM historical_orders\n--\nSELECT * FROM current_orders;`, `SELECT * FROM historical_orders\nUNION ALL\nSELECT * FROM current_orders;`, 'Same standard SQL operator.'),
    bigquery: V('sql', `SELECT * FROM historical_orders\n--\nSELECT * FROM current_orders;`, `SELECT * FROM historical_orders\nUNION ALL\nSELECT * FROM current_orders;`, 'GoogleSQL uses UNION ALL for append semantics.'),
    pandas: V('python', `result = pd.concat(\n    # frames\n    ignore_index=True\n)`, `result = pd.concat([historical_orders, current_orders], ignore_index=True)`, 'pd.concat stacks DataFrames along rows by default.'),
    pyspark: V('python', `result = historical_orders.#(current_orders)`, `result = historical_orders.unionByName(current_orders)`, 'unionByName is safer than positional union when schemas are logically aligned by name.'),
  }}),

  // BigQuery-specific
  E({ id:'bq-qualify', track:'eng-bigquery', level:'Beginner', title:'Filter a window result with QUALIFY', concept:'QUALIFY filters rows after analytic/window functions are computed.', context:'events(user_id, event_time).', task:'Keep the latest event for each user using one SELECT.', hints:['ROW_NUMBER inside each user.','QUALIFY rank = 1.'], pitfall:'WHERE runs before window functions and cannot filter the window alias directly.', variants:{
    bigquery: V('sql', `SELECT *\nFROM events\nQUALIFY ROW_NUMBER() OVER (\n  PARTITION BY user_id ORDER BY event_time DESC\n) = --\n`, `SELECT *\nFROM events\nQUALIFY ROW_NUMBER() OVER (\n  PARTITION BY user_id ORDER BY event_time DESC\n) = 1;`, 'QUALIFY is evaluated after the window stage.'),
    duckdb: V('sql', `SELECT *\nFROM events\nQUALIFY ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY event_time DESC) = --`, `SELECT *\nFROM events\nQUALIFY ROW_NUMBER() OVER (PARTITION BY user_id ORDER BY event_time DESC) = 1;`, 'DuckDB supports the same QUALIFY pattern.'),
  }}),
  E({ id:'bq-unnest', track:'eng-bigquery', level:'Intermediate', title:'Flatten an ARRAY with UNNEST', concept:'BigQuery can store repeated values as ARRAYs; UNNEST turns array elements into rows.', context:'orders(order_id, item_ids ARRAY<INT64>).', task:'Return one row per order_id/item_id pair.', hints:['Put UNNEST in FROM.','Alias the array element.'], pitfall:'UNNEST changes row cardinality; an order with five items becomes five rows.', variants:{
    bigquery: V('sql', `SELECT o.order_id, item_id\nFROM orders AS o\nCROSS JOIN UNNEST(#) AS item_id;`, `SELECT o.order_id, item_id\nFROM orders AS o\nCROSS JOIN UNNEST(o.item_ids) AS item_id;`, 'UNNEST emits one row for each array element.'),
    pyspark: V('python', `from pyspark.sql import functions as F\nresult = orders.withColumn("item_id", #).select("order_id", "item_id")`, `from pyspark.sql import functions as F\nresult = orders.withColumn("item_id", F.explode("item_ids")).select("order_id", "item_id")`, 'PySpark explode is the closest DataFrame analogue.'),
    pandas: V('python', `result = orders.#("item_ids").rename(columns={"item_ids": "item_id"})`, `result = orders.explode("item_ids").rename(columns={"item_ids": "item_id"})`, 'pandas explode expands list-like cells into rows.'),
  }}),
  E({ id:'bq-safe-divide', track:'eng-bigquery', level:'Beginner', title:'Calculate a safe conversion rate', concept:'Division by zero should be handled explicitly in analytical queries.', context:'campaigns(clicks, impressions).', task:'Return clicks / impressions without raising an error when impressions = 0.', hints:['BigQuery has SAFE_DIVIDE.'], pitfall:'A plain division can fail or need explicit zero handling depending on engine/types.', variants:{
    bigquery: V('sql', `SELECT SAFE_DIVIDE(#, #) AS ctr\nFROM campaigns;`, `SELECT SAFE_DIVIDE(clicks, impressions) AS ctr\nFROM campaigns;`, 'SAFE_DIVIDE returns NULL instead of failing on division by zero.'),
    tsql: V('sql', `SELECT clicks * 1.0 / NULLIF(impressions, 0) AS ctr\nFROM dbo.campaigns;`, `SELECT clicks * 1.0 / NULLIF(impressions, 0) AS ctr\nFROM dbo.campaigns;`, 'T-SQL commonly uses NULLIF(denominator, 0) to guard division.'),
  }}),
  E({ id:'bq-array-agg', track:'eng-bigquery', level:'Intermediate', title:'Collect recent events into an array', concept:'ARRAY_AGG can collect grouped rows into an ordered repeated value.', context:'events(user_id, event_time, event_name).', task:'Return one row per user with an array of event_name ordered newest first.', hints:['GROUP BY user_id.','ARRAY_AGG supports ORDER BY.'], pitfall:'Without ordering, array element order should not be assumed.', variants:{
    bigquery: V('sql', `SELECT user_id,\n       ARRAY_AGG(event_name ORDER BY # DESC) AS events\nFROM events\nGROUP BY user_id;`, `SELECT user_id,\n       ARRAY_AGG(event_name ORDER BY event_time DESC) AS events\nFROM events\nGROUP BY user_id;`, 'BigQuery arrays can preserve an explicit aggregation order.'),
  }}),

  // PySpark-specific
  E({ id:'sp-explode', track:'eng-pyspark', level:'Beginner', title:'Explode an array column', concept:'explode turns each array element into a separate row.', context:'orders(order_id, item_ids ARRAY).', task:'Create one row per item_id.', hints:['Use functions.explode.'], pitfall:'explode drops rows where the array is null; explode_outer has different null-preservation behavior.', variants:{
    pyspark: V('python', `from pyspark.sql import functions as F\nresult = orders.withColumn("item_id", #)`, `from pyspark.sql import functions as F\nresult = orders.withColumn("item_id", F.explode("item_ids"))`, 'explode is the distributed equivalent of flattening a repeated field.'),
    pandas: V('python', `result = orders.#("item_ids")`, `result = orders.explode("item_ids")`, 'pandas has a similarly named explode operation.'),
  }}),
  E({ id:'sp-broadcast', track:'eng-pyspark', level:'Intermediate', title:'Broadcast a small dimension table', concept:'A broadcast join can avoid shuffling a large fact table when one side is genuinely small.', context:'sales is very large; products is a small dimension.', task:'Join sales to products while explicitly broadcasting products.', hints:['Import broadcast from pyspark.sql.functions.'], pitfall:'Broadcasting a table that is not small can exhaust executor memory.', variants:{
    pyspark: V('python', `from pyspark.sql.functions import broadcast\nresult = sales.join(\n    # broadcast small side\n    on="product_id", how="left"\n)`, `from pyspark.sql.functions import broadcast\nresult = sales.join(\n    broadcast(products),\n    on="product_id", how="left"\n)`, 'broadcast provides a join hint that the small relation can be sent to workers.'),
  }}),
  E({ id:'sp-repartition', track:'eng-pyspark', level:'Intermediate', title:'Repartition by a business key before a heavy operation', concept:'repartition changes distributed partitioning and triggers a shuffle.', context:'events is a large DataFrame and downstream work is heavily keyed by customer_id.', task:'Create 200 partitions by customer_id.', hints:['repartition takes partition count and columns.'], pitfall:'repartition is not a free optimization; it shuffles data and can make a pipeline slower when unnecessary.', variants:{
    pyspark: V('python', `result = events.repartition(# count, # key)`, `result = events.repartition(200, "customer_id")`, 'Explicit repartitioning is a physical-distribution decision, not a row transformation.'),
  }}),
  E({ id:'eng-sp-withcolumn', track:'eng-pyspark', level:'Beginner', title:'Derive a normalized email column', concept:'PySpark transformations build Column expressions rather than iterating through Python rows.', context:'customers(email).', task:'Create email_normalized as trimmed lowercase email.', hints:['Use F.trim and F.lower.','Nest Column expressions.'], pitfall:'Do not collect rows to Python just to call str.lower() one row at a time.', variants:{
    pyspark: V('python', `from pyspark.sql import functions as F\nresult = customers.withColumn(\n    "email_normalized",\n    # expression\n)`, `from pyspark.sql import functions as F\nresult = customers.withColumn(\n    "email_normalized",\n    F.lower(F.trim(F.col("email")))\n)`, 'Column functions are translated into Spark execution plans.'),
    pandas: V('python', `customers["email_normalized"] = customers["email"].str.#.str.#`, `customers["email_normalized"] = customers["email"].str.strip().str.lower()`, 'pandas vectorized string methods express the same logical transformation.'),
  }}),

  // pandas-specific
  E({ id:'pd-merge-validate', track:'eng-pandas', level:'Intermediate', title:'Validate a many-to-one merge', concept:'pandas merge can assert expected key cardinality to catch accidental row multiplication.', context:'orders has many rows per customer_id; customers should have one row per customer_id.', task:'Left-merge customers onto orders and validate many-to-one cardinality.', hints:['Use validate="many_to_one".'], pitfall:'A duplicated dimension key can silently multiply fact rows if you never validate the relationship.', variants:{
    pandas: V('python', `result = orders.merge(\n    customers,\n    on="customer_id", how="left",\n    validate=#\n)`, `result = orders.merge(\n    customers,\n    on="customer_id", how="left",\n    validate="many_to_one"\n)`, 'The validation raises if the right-side key is not unique as expected.'),
  }}),
  E({ id:'pd-transform-share', track:'eng-pandas', level:'Intermediate', title:'Calculate each row share of its customer total', concept:'GroupBy.transform returns a same-length result aligned to the original rows.', context:'orders(customer_id, amount).', task:'Add customer_total and amount_share without collapsing the DataFrame.', hints:['transform("sum") preserves row count.'], pitfall:'agg collapses to one row per group; transform is for group metrics returned to each original row.', variants:{
    pandas: V('python', `df["customer_total"] = df.groupby(#)["amount"].transform(#)\ndf["amount_share"] = --`, `df["customer_total"] = df.groupby("customer_id")["amount"].transform("sum")\ndf["amount_share"] = df["amount"] / df["customer_total"]`, 'transform broadcasts a group result back to rows at the original index.'),
    pyspark: V('python', `from pyspark.sql import functions as F\nfrom pyspark.sql.window import Window\nw = Window.partitionBy("customer_id")\nresult = df.withColumn("customer_total", #).withColumn("amount_share", #)`, `from pyspark.sql import functions as F\nfrom pyspark.sql.window import Window\nw = Window.partitionBy("customer_id")\nresult = (df.withColumn("customer_total", F.sum("amount").over(w))\n            .withColumn("amount_share", F.col("amount") / F.col("customer_total")))`, 'A partition-only Spark window is the closest equivalent to pandas transform for this case.'),
  }}),
  E({ id:'pd-rank-group', track:'eng-pandas', level:'Intermediate', title:'Dense rank inside each group', concept:'Group-wise ranking creates a row-level metric without collapsing groups.', context:'employees(department, wage).', task:'Add wage_rank where highest distinct wage is rank 1 in each department.', hints:['Group wage by department.','Use rank(method="dense", ascending=False).'], pitfall:'The default pandas rank method averages ties, which differs from DENSE_RANK.', variants:{
    pandas: V('python', `df["wage_rank"] = (\n    df.groupby(#)["wage"]\n      .rank(method=#, ascending=#)\n)`, `df["wage_rank"] = (\n    df.groupby("department")["wage"]\n      .rank(method="dense", ascending=False)\n)`, 'method="dense" matches SQL DENSE_RANK tie behavior.'),
    tsql: V('sql', `SELECT *, DENSE_RANK() OVER (PARTITION BY department ORDER BY wage DESC) AS wage_rank\nFROM dbo.employees;`, `SELECT *, DENSE_RANK() OVER (PARTITION BY department ORDER BY wage DESC) AS wage_rank\nFROM dbo.employees;`, 'SQL makes the ranking intent explicit with DENSE_RANK.'),
  }}),
  E({ id:'pd-cross-merge', track:'eng-pandas', level:'Beginner', title:'Create a Cartesian product with merge', concept:'pandas supports a cross merge for every-left-row × every-right-row combinations.', context:'sizes(size_code); brands(brand_name).', task:'Create every size/brand combination.', hints:['merge(..., how="cross").'], pitfall:'Cartesian products grow multiplicatively and can become huge.', variants:{
    pandas: V('python', `grid = sizes.merge(brands, how=#)`, `grid = sizes.merge(brands, how="cross")`, 'pandas cross merge expresses the Cartesian product directly.'),
    tsql: V('sql', `SELECT s.size_code, b.brand_name\nFROM dbo.sizes s\n-- join\ndbo.brands b;`, `SELECT s.size_code, b.brand_name\nFROM dbo.sizes s\nCROSS JOIN dbo.brands b;`, 'CROSS JOIN is the SQL equivalent.'),
  }}),
]

export function getEngineVariant(challenge, engine) {
  const available = Object.keys(challenge.variants)
  const selected = challenge.variants[engine] ? engine : available[0]
  const variant = challenge.variants[selected]
  return {
    ...challenge,
    engine: selected,
    engineLabel: engineDefinitions[selected]?.label ?? selected,
    language: variant.language,
    starter: variant.starter,
    solution: variant.solution,
    solutionExplanation: variant.explanation,
    availableEngines: available,
  }
}
